from BaseClasses import Item, ItemClassification
from typing import NamedTuple, Dict, List

class StagesData(NamedTuple):
    code: int
    item_name: str
    classification: ItemClassification
    region: str

class TrapItemData(NamedTuple):
    code: int
    item_name: str
    classification: ItemClassification
    weight: int

class SRItem(Item):
    game = "Stick Ranger"

# Stage start ID 11000
stages = [
    # StagesData(11000, "Unlock Town", ItemClassification.useful, "Town"),
    # StagesData(11001, "Unlock Opening Street", ItemClassification.progression, "Grassland"),
    StagesData(11002, "Unlock Grassland 1", ItemClassification.progression, "Grassland"),
    StagesData(11003, "Unlock Grassland 2", ItemClassification.progression, "Grassland"),
    StagesData(11004, "Unlock Grassland 3", ItemClassification.progression, "Grassland"),
    StagesData(11005, "Unlock Grassland 4", ItemClassification.progression, "Grassland"),
    StagesData(11006, "Unlock Grassland 5", ItemClassification.progression, "Grassland"),
    StagesData(11007, "Unlock Grassland 6", ItemClassification.progression, "Grassland"),
    StagesData(11008, "Unlock Grassland 7", ItemClassification.progression, "Grassland"),
    StagesData(11009, "Unlock Castle Gate", ItemClassification.progression, "Grassland"),
    StagesData(11010, "Unlock Castle", ItemClassification.progression, "Boss"),
    StagesData(11011, "Unlock Hill Country 1", ItemClassification.progression, "Grassland"),
    StagesData(11012, "Unlock Hill Country 2", ItemClassification.progression, "Grassland"),
    StagesData(11013, "Unlock Hill Country 3", ItemClassification.progression, "Grassland"),
    StagesData(11014, "Unlock Lake", ItemClassification.progression, "Grassland"),
    StagesData(11015, "Unlock Forest 1", ItemClassification.progression, "Grassland"),
    StagesData(11016, "Unlock Forest 2", ItemClassification.progression, "Grassland"),
    StagesData(11017, "Unlock Cavern 1", ItemClassification.progression, "Grassland"),
    StagesData(11018, "Unlock Cavern 2", ItemClassification.progression, "Grassland"),
    StagesData(11019, "Unlock Cavern 3", ItemClassification.progression, "Grassland"),
    StagesData(11020, "Unlock Village", ItemClassification.useful, "Town"),
    StagesData(11021, "Unlock Seaside 1", ItemClassification.progression, "Sea"),
    StagesData(11022, "Unlock Seaside 2", ItemClassification.progression, "Sea"),
    StagesData(11023, "Unlock Seaside 3", ItemClassification.progression, "Sea"),
    StagesData(11024, "Unlock Seaside 4", ItemClassification.progression, "Sea"),
    StagesData(11025, "Unlock Submarine 1", ItemClassification.progression, "Sea"),
    StagesData(11026, "Unlock Submarine 2", ItemClassification.progression, "Sea"),
    StagesData(11027, "Unlock Submarine 3", ItemClassification.progression, "Sea"),
    StagesData(11028, "Unlock Submarine 4", ItemClassification.progression, "Sea"),
    StagesData(11029, "Unlock Submarine Shrine", ItemClassification.progression, "Boss"),
    StagesData(11030, "Unlock Mist Grove 1", ItemClassification.progression, "Sea"),
    StagesData(11031, "Unlock Mist Grove 2", ItemClassification.progression, "Sea"),
    StagesData(11032, "Unlock Mist Grove 3", ItemClassification.progression, "Sea"),
    StagesData(11033, "Unlock ???", ItemClassification.progression, "Sea"),
    StagesData(11034, "Unlock Desert 1", ItemClassification.progression, "Desert"),
    StagesData(11035, "Unlock Desert 2", ItemClassification.progression, "Desert"),
    StagesData(11036, "Unlock Desert 3", ItemClassification.progression, "Desert"),
    StagesData(11037, "Unlock Desert 4", ItemClassification.progression, "Desert"),
    StagesData(11038, "Unlock Desert 5", ItemClassification.progression, "Desert"),
    StagesData(11039, "Unlock Oasis", ItemClassification.progression, "Desert"),
    StagesData(11040, "Unlock Desert 6", ItemClassification.progression, "Desert"),
    StagesData(11041, "Unlock Desert 7", ItemClassification.progression, "Desert"),
    StagesData(11042, "Unlock Pyramid", ItemClassification.progression, "Boss"),
    StagesData(11043, "Unlock Desert 8", ItemClassification.progression, "Desert"),
    StagesData(11044, "Unlock Beach 1", ItemClassification.progression, "Desert"),
    StagesData(11045, "Unlock Beach 2", ItemClassification.progression, "Desert"),
    StagesData(11046, "Unlock Beach 3", ItemClassification.progression, "Desert"),
    StagesData(11047, "Unlock Resort", ItemClassification.useful, "Town"),
    StagesData(11048, "Unlock Cavern 4", ItemClassification.progression, "Ice"),
    StagesData(11049, "Unlock Cavern 5", ItemClassification.progression, "Ice"),
    StagesData(11050, "Unlock Cavern 6", ItemClassification.progression, "Ice"),
    StagesData(11051, "Unlock Snowfield 1", ItemClassification.progression, "Ice"),
    StagesData(11052, "Unlock Snowfield 2", ItemClassification.progression, "Ice"),
    StagesData(11053, "Unlock Mountain 1", ItemClassification.progression, "Ice"),
    StagesData(11054, "Unlock Mountain 2", ItemClassification.progression, "Ice"),
    StagesData(11055, "Unlock Mountaintop", ItemClassification.progression, "Ice"),
    StagesData(11056, "Unlock Snowfield 3", ItemClassification.progression, "Ice"),
    StagesData(11057, "Unlock Snowfield 4", ItemClassification.progression, "Ice"),
    StagesData(11058, "Unlock Snowfield 5", ItemClassification.progression, "Ice"),
    StagesData(11059, "Unlock Snowfield 6", ItemClassification.progression, "Ice"),
    StagesData(11060, "Unlock Snowfield 7", ItemClassification.progression, "Ice"),
    StagesData(11061, "Unlock Snowfield 8", ItemClassification.progression, "Ice"),
    StagesData(11062, "Unlock Frozen Lake", ItemClassification.progression, "Ice"),
    StagesData(11063, "Unlock Ice Castle", ItemClassification.progression, "Boss"),
    StagesData(11064, "Unlock Snowfield 9", ItemClassification.progression, "Hell"),
    StagesData(11065, "Unlock Beach 4", ItemClassification.progression, "Hell"),
    StagesData(11066, "Unlock Forest 3", ItemClassification.progression, "Hell"),
    StagesData(11067, "Unlock Forest 4", ItemClassification.progression, "Hell"),
    StagesData(11068, "Unlock Forest 5", ItemClassification.progression, "Hell"),
    StagesData(11069, "Unlock Forest 6", ItemClassification.progression, "Hell"),
    StagesData(11070, "Unlock Forget Tree", ItemClassification.useful, "Town"),
    StagesData(11071, "Unlock !!!", ItemClassification.progression, "Hell"),
    StagesData(11072, "Unlock Hell 1", ItemClassification.progression, "Hell"),
    StagesData(11073, "Unlock Hell 2", ItemClassification.progression, "Hell"),
    StagesData(11074, "Unlock Hell 3", ItemClassification.progression, "Hell"),
    StagesData(11075, "Unlock Hell 4", ItemClassification.progression, "Hell"),
    StagesData(11076, "Unlock Hell 5", ItemClassification.progression, "Hell"),
    StagesData(11077, "Unlock Island", ItemClassification.useful, "Town"),
    StagesData(11078, "Unlock Hell 6", ItemClassification.progression, "Hell"),
    StagesData(11079, "Unlock Inferno 1", ItemClassification.progression, "Hell"),
    StagesData(11080, "Unlock Inferno 2", ItemClassification.progression, "Hell"),
    StagesData(11081, "Unlock Inferno 3", ItemClassification.progression, "Hell"),
    StagesData(11082, "Unlock Blood Lake", ItemClassification.progression, "Hell"),
    StagesData(11083, "Unlock Cavern 7", ItemClassification.progression, "Hell"),
    StagesData(11084, "Unlock Cavern 8", ItemClassification.progression, "Hell"),
    StagesData(11085, "Unlock Hell 7", ItemClassification.progression, "Hell"),
    StagesData(11086, "Unlock Hell 8", ItemClassification.progression, "Hell"),
    StagesData(11087, "Unlock Hell Gate", ItemClassification.progression, "Hell"),
    StagesData(11088, "Unlock Hell Castle", ItemClassification.progression, "Boss"),
    StagesData(11089, "Unlock Volcano", ItemClassification.progression, "Hell"),
]

levelups = [
    StagesData(11100 + i, "Levelup", ItemClassification.progression, "any")
    for i in range(98)
]

filler = [
    StagesData(12003, "glove", ItemClassification.filler, "any"),
    StagesData(12007, "mach punch", ItemClassification.filler, "any"),
    StagesData(12011, "thunder glove", ItemClassification.filler, "any"),
    StagesData(12015, "fire glove", ItemClassification.filler, "any"),
    StagesData(12054, "poison glove", ItemClassification.filler, "any"),
    StagesData(12064, "freeze glove", ItemClassification.filler, "any"),
    StagesData(12068, "needle glove", ItemClassification.filler, "any"),
    StagesData(12072, "spark glove", ItemClassification.filler, "any"),
    StagesData(12116, "sonic punch", ItemClassification.filler, "any"),
    StagesData(12121, "thunder knuckle", ItemClassification.filler, "any"),
    StagesData(12131, "fire knuckle", ItemClassification.filler, "any"),
    StagesData(12137, "mach knuckle", ItemClassification.filler, "any"),
    StagesData(12153, "poison knuckle", ItemClassification.filler, "any"),
    StagesData(12178, "freeze knuckle", ItemClassification.filler, "any"),
    StagesData(12202, "needle knuckle", ItemClassification.filler, "any"),
    StagesData(12214, "spark knuckle", ItemClassification.filler, "any"),
    StagesData(12226, "sonic knuckle", ItemClassification.filler, "any"),
    StagesData(12253, "thunder claw", ItemClassification.filler, "any"),
    StagesData(12270, "charge punch", ItemClassification.filler, "any"),
    StagesData(12312, "fire claw", ItemClassification.filler, "any"),
    StagesData(12328, "mach claw", ItemClassification.filler, "any"),
    StagesData(12345, "poison claw", ItemClassification.filler, "any"),
    StagesData(12360, "freeze claw", ItemClassification.filler, "any"),
    StagesData(12394, "needle claw", ItemClassification.filler, "any"),
    StagesData(12410, "spark claw", ItemClassification.filler, "any"),
    StagesData(12429, "sonic claw", ItemClassification.filler, "any"),
    StagesData(12451, "thunder cestus", ItemClassification.filler, "any"),
    StagesData(12471, "fire cestus", ItemClassification.filler, "any"),
    StagesData(12479, "mach cestus", ItemClassification.filler, "any"),
    StagesData(12496, "poison cestus", ItemClassification.filler, "any"),
    StagesData(12504, "freeze cestus", ItemClassification.filler, "any"),
    StagesData(12512, "needle cestus", ItemClassification.filler, "any"),
    StagesData(12520, "spark cestus", ItemClassification.filler, "any"),
    StagesData(12549, "sonic cestus", ItemClassification.filler, "any"),
    StagesData(12004, "sword", ItemClassification.filler, "any"),
    StagesData(12008, "iron sword", ItemClassification.filler, "any"),
    StagesData(12012, "fire sword", ItemClassification.filler, "any"),
    StagesData(12016, "thunder sword", ItemClassification.filler, "any"),
    StagesData(12055, "ice sword", ItemClassification.filler, "any"),
    StagesData(12065, "long sword", ItemClassification.filler, "any"),
    StagesData(12069, "lightsaber", ItemClassification.filler, "any"),
    StagesData(12073, "flame sword", ItemClassification.filler, "any"),
    StagesData(12117, "frozen sword", ItemClassification.filler, "any"),
    StagesData(12122, "sabel", ItemClassification.filler, "any"),
    StagesData(12132, "fire sabel", ItemClassification.filler, "any"),
    StagesData(12138, "thunder sabel", ItemClassification.filler, "any"),
    StagesData(12154, "ice sabel", ItemClassification.filler, "any"),
    StagesData(12179, "long sabel", ItemClassification.filler, "any"),
    StagesData(12203, "lightsaber", ItemClassification.filler, "any"),
    StagesData(12215, "flame sabel", ItemClassification.filler, "any"),
    StagesData(12227, "frozen sabel", ItemClassification.filler, "any"),
    StagesData(12254, "blade", ItemClassification.filler, "any"),
    StagesData(12271, "wooden sword", ItemClassification.filler, "any"),
    StagesData(12313, "fire blade", ItemClassification.filler, "any"),
    StagesData(12329, "thunder blade", ItemClassification.filler, "any"),
    StagesData(12346, "ice blade", ItemClassification.filler, "any"),
    StagesData(12361, "long blade", ItemClassification.filler, "any"),
    StagesData(12395, "lightsaber", ItemClassification.filler, "any"),
    StagesData(12411, "flame blade", ItemClassification.filler, "any"),
    StagesData(12430, "frozen blade", ItemClassification.filler, "any"),
    StagesData(12452, "GreatSword", ItemClassification.filler, "any"),
    StagesData(12472, "fire GS", ItemClassification.filler, "any"),
    StagesData(12480, "thunder GS", ItemClassification.filler, "any"),
    StagesData(12497, "ice GS", ItemClassification.filler, "any"),
    StagesData(12505, "long GS", ItemClassification.filler, "any"),
    StagesData(12513, "lightsaber", ItemClassification.filler, "any"),
    StagesData(12521, "flame GS", ItemClassification.filler, "any"),
    StagesData(12550, "frozen GS", ItemClassification.filler, "any"),
    StagesData(12005, "bow", ItemClassification.filler, "any"),
    StagesData(12009, "triple shot", ItemClassification.filler, "any"),
    StagesData(12013, "poison arrow", ItemClassification.filler, "any"),
    StagesData(12017, "double arrow", ItemClassification.filler, "any"),
    StagesData(12056, "fire arrow", ItemClassification.filler, "any"),
    StagesData(12066, "triple arrow", ItemClassification.filler, "any"),
    StagesData(12070, "quad arrow", ItemClassification.filler, "any"),
    StagesData(12074, "oct arrow", ItemClassification.filler, "any"),
    StagesData(12118, "double poison", ItemClassification.filler, "any"),
    StagesData(12123, "quint shot", ItemClassification.filler, "any"),
    StagesData(12133, "double fire", ItemClassification.filler, "any"),
    StagesData(12139, "double iron arrow", ItemClassification.filler, "any"),
    StagesData(12155, "triple iron arrow", ItemClassification.filler, "any"),
    StagesData(12180, "triple poison", ItemClassification.filler, "any"),
    StagesData(12204, "fire shot", ItemClassification.filler, "any"),
    StagesData(12216, "quad iron arrow", ItemClassification.filler, "any"),
    StagesData(12228, "nonuple arrow", ItemClassification.filler, "any"),
    StagesData(12255, "poison shot", ItemClassification.filler, "any"),
    StagesData(12272, "pyramid arrow", ItemClassification.filler, "any"),
    StagesData(12314, "flame arrow", ItemClassification.filler, "any"),
    StagesData(12330, "sept shot", ItemClassification.filler, "any"),
    StagesData(12347, "pierce arrow", ItemClassification.filler, "any"),
    StagesData(12362, "quint poison", ItemClassification.filler, "any"),
    StagesData(12396, "double flame", ItemClassification.filler, "any"),
    StagesData(12402, "Indra arrow", ItemClassification.filler, "any"),
    StagesData(12412, "quad steel arrow", ItemClassification.filler, "any"),
    StagesData(12431, "undecuple arrow", ItemClassification.filler, "any"),
    StagesData(12453, "nonuple shot", ItemClassification.filler, "any"),
    StagesData(12473, "flame shot", ItemClassification.filler, "any"),
    StagesData(12481, "oct poison", ItemClassification.filler, "any"),
    StagesData(12498, "double hell fire", ItemClassification.filler, "any"),
    StagesData(12506, "quint gold arrow", ItemClassification.filler, "any"),
    StagesData(12514, "vigintuple arrow", ItemClassification.filler, "any"),
    StagesData(12522, "oct poison shot", ItemClassification.filler, "any"),
    StagesData(12551, "hell fire shot", ItemClassification.filler, "any"),
    StagesData(12006, "magic", ItemClassification.filler, "any"),
    StagesData(12010, "explosion", ItemClassification.filler, "any"),
    StagesData(12014, "ice", ItemClassification.filler, "any"),
    StagesData(12018, "fire", ItemClassification.filler, "any"),
    StagesData(12057, "thunder", ItemClassification.filler, "any"),
    StagesData(12067, "freeze", ItemClassification.filler, "any"),
    StagesData(12071, "blizzard", ItemClassification.filler, "any"),
    StagesData(12075, "volcano", ItemClassification.filler, "any"),
    StagesData(12119, "thunder storm", ItemClassification.filler, "any"),
    StagesData(12124, "delta explosion", ItemClassification.filler, "any"),
    StagesData(12134, "icicle", ItemClassification.filler, "any"),
    StagesData(12140, "fire rise", ItemClassification.filler, "any"),
    StagesData(12156, "big thunder", ItemClassification.filler, "any"),
    StagesData(12181, "big icicle", ItemClassification.filler, "any"),
    StagesData(12205, "ice meteor", ItemClassification.filler, "any"),
    StagesData(12217, "super volcano", ItemClassification.filler, "any"),
    StagesData(12229, "thunder spear", ItemClassification.filler, "any"),
    StagesData(12256, "time explosion", ItemClassification.filler, "any"),
    StagesData(12273, "atomic ray", ItemClassification.filler, "any"),
    StagesData(12315, "ice spike", ItemClassification.filler, "any"),
    StagesData(12331, "inferno", ItemClassification.filler, "any"),
    StagesData(12348, "electric shock", ItemClassification.filler, "any"),
    StagesData(12363, "freeze explosion", ItemClassification.filler, "any"),
    StagesData(12397, "ice orb", ItemClassification.filler, "any"),
    StagesData(12413, "lava", ItemClassification.filler, "any"),
    StagesData(12432, "thunder orb", ItemClassification.filler, "any"),
    StagesData(12454, "spread explosion", ItemClassification.filler, "any"),
    StagesData(12474, "ice bolt", ItemClassification.filler, "any"),
    StagesData(12482, "hell fire", ItemClassification.filler, "any"),
    StagesData(12499, "lightning", ItemClassification.filler, "any"),
    StagesData(12507, "permafrost", ItemClassification.filler, "any"),
    StagesData(12515, "ice missile", ItemClassification.filler, "any"),
    StagesData(12523, "pyroclastic flow", ItemClassification.filler, "any"),
    StagesData(12552, "thunderbolt", ItemClassification.filler, "any"),
    StagesData(12058, "staff", ItemClassification.filler, "any"),
    StagesData(12060, "staff of wood", ItemClassification.filler, "any"),
    StagesData(12061, "long staff", ItemClassification.filler, "any"),
    StagesData(12062, "staff of thunder", ItemClassification.filler, "any"),
    StagesData(12063, "staff of ice", ItemClassification.filler, "any"),
    StagesData(12115, "battle staff", ItemClassification.filler, "any"),
    StagesData(12126, "staff of fire", ItemClassification.filler, "any"),
    StagesData(12127, "lightning staff", ItemClassification.filler, "any"),
    StagesData(12128, "staff of poison", ItemClassification.filler, "any"),
    StagesData(12129, "long wood staff", ItemClassification.filler, "any"),
    StagesData(12135, "staff of freeze", ItemClassification.filler, "any"),
    StagesData(12141, "staff of light", ItemClassification.filler, "any"),
    StagesData(12157, "staff of flame", ItemClassification.filler, "any"),
    StagesData(12182, "combat staff", ItemClassification.filler, "any"),
    StagesData(12206, "staff of poisoner", ItemClassification.filler, "any"),
    StagesData(12218, "long iron staff", ItemClassification.filler, "any"),
    StagesData(12230, "staff of icicle", ItemClassification.filler, "any"),
    StagesData(12257, "explosion staff", ItemClassification.filler, "any"),
    StagesData(12274, "high light staff", ItemClassification.filler, "any"),
    StagesData(12316, "warrior staff", ItemClassification.filler, "any"),
    StagesData(12332, "inferno staff", ItemClassification.filler, "any"),
    StagesData(12349, "electric staff", ItemClassification.filler, "any"),
    StagesData(12364, "long silver staff", ItemClassification.filler, "any"),
    StagesData(12398, "poisonous staff", ItemClassification.filler, "any"),
    StagesData(12414, "freeze exp staff", ItemClassification.filler, "any"),
    StagesData(12433, "mega exp staff", ItemClassification.filler, "any"),
    StagesData(12455, "strike rod", ItemClassification.filler, "any"),
    StagesData(12475, "inferno rod", ItemClassification.filler, "any"),
    StagesData(12483, "thunder rod", ItemClassification.filler, "any"),
    StagesData(12500, "long gold rod", ItemClassification.filler, "any"),
    StagesData(12508, "poisonous rod", ItemClassification.filler, "any"),
    StagesData(12516, "freeze exp rod", ItemClassification.filler, "any"),
    StagesData(12524, "giga exp rod", ItemClassification.filler, "any"),
    StagesData(12553, "power rod", ItemClassification.filler, "any"),
    StagesData(12076, "gun", ItemClassification.filler, "any"),
    StagesData(12077, "handgun", ItemClassification.filler, "any"),
    StagesData(12078, "submachine-gun", ItemClassification.filler, "any"),
    StagesData(12079, "shotgun", ItemClassification.filler, "any"),
    StagesData(12080, "rifle", ItemClassification.filler, "any"),
    StagesData(12081, "grenade", ItemClassification.filler, "any"),
    StagesData(12082, "laser gun", ItemClassification.filler, "any"),
    StagesData(12083, "bazooka", ItemClassification.filler, "any"),
    StagesData(12120, "homing laser", ItemClassification.filler, "any"),
    StagesData(12125, "beretta", ItemClassification.filler, "any"),
    StagesData(12136, "uzi", ItemClassification.filler, "any"),
    StagesData(12142, "remington", ItemClassification.filler, "any"),
    StagesData(12158, "sniper rifle", ItemClassification.filler, "any"),
    StagesData(12183, "grenade launcher", ItemClassification.filler, "any"),
    StagesData(12207, "laser beam gun", ItemClassification.filler, "any"),
    StagesData(12219, "cannon", ItemClassification.filler, "any"),
    StagesData(12231, "homing laser beam", ItemClassification.filler, "any"),
    StagesData(12258, "3-round burst", ItemClassification.filler, "any"),
    StagesData(12275, "missile", ItemClassification.filler, "any"),
    StagesData(12317, "mini uzi", ItemClassification.filler, "any"),
    StagesData(12333, "scattergun", ItemClassification.filler, "any"),
    StagesData(12350, "hunting gun", ItemClassification.filler, "any"),
    StagesData(12365, "M9 grenade", ItemClassification.filler, "any"),
    StagesData(12399, "power laser gun", ItemClassification.filler, "any"),
    StagesData(12403, "Napalm bomb", ItemClassification.filler, "any"),
    StagesData(12415, "wave cannon", ItemClassification.filler, "any"),
    StagesData(12434, "pierce homing", ItemClassification.filler, "any"),
    StagesData(12456, "magnum", ItemClassification.filler, "any"),
    StagesData(12476, "micro uzi", ItemClassification.filler, "any"),
    StagesData(12484, "triple shotgun", ItemClassification.filler, "any"),
    StagesData(12501, "rail gun", ItemClassification.filler, "any"),
    StagesData(12509, "napalm gun", ItemClassification.filler, "any"),
    StagesData(12517, "slow laser gun", ItemClassification.filler, "any"),
    StagesData(12525, "rocket launcher", ItemClassification.filler, "any"),
    StagesData(12554, "homing laser wave", ItemClassification.filler, "any"),
    StagesData(12188, "whip", ItemClassification.filler, "any"),
    StagesData(12189, "stone whip", ItemClassification.filler, "any"),
    StagesData(12190, "fire whip", ItemClassification.filler, "any"),
    StagesData(12191, "iron whip", ItemClassification.filler, "any"),
    StagesData(12192, "thunder whip", ItemClassification.filler, "any"),
    StagesData(12193, "ice whip", ItemClassification.filler, "any"),
    StagesData(12194, "thorn whip", ItemClassification.filler, "any"),
    StagesData(12195, "poison whip", ItemClassification.filler, "any"),
    StagesData(12196, "explosion whip", ItemClassification.filler, "any"),
    StagesData(12197, "stone chain", ItemClassification.filler, "any"),
    StagesData(12198, "fire chain", ItemClassification.filler, "any"),
    StagesData(12199, "iron chain", ItemClassification.filler, "any"),
    StagesData(12200, "thunder chain", ItemClassification.filler, "any"),
    StagesData(12201, "ice chain", ItemClassification.filler, "any"),
    StagesData(12208, "thorn chain", ItemClassification.filler, "any"),
    StagesData(12220, "poison chain", ItemClassification.filler, "any"),
    StagesData(12232, "explosion chain", ItemClassification.filler, "any"),
    StagesData(12259, "stone flail", ItemClassification.filler, "any"),
    StagesData(12276, "freeze whip", ItemClassification.filler, "any"),
    StagesData(12318, "fire flail", ItemClassification.filler, "any"),
    StagesData(12334, "iron flail", ItemClassification.filler, "any"),
    StagesData(12351, "thunder flail", ItemClassification.filler, "any"),
    StagesData(12366, "ice flail", ItemClassification.filler, "any"),
    StagesData(12400, "thorn flail", ItemClassification.filler, "any"),
    StagesData(12416, "poison flail", ItemClassification.filler, "any"),
    StagesData(12435, "explosion flail", ItemClassification.filler, "any"),
    StagesData(12457, "morning star", ItemClassification.filler, "any"),
    StagesData(12477, "stone ms", ItemClassification.filler, "any"),
    StagesData(12485, "fire ms", ItemClassification.filler, "any"),
    StagesData(12502, "thunder ms", ItemClassification.filler, "any"),
    StagesData(12510, "ice ms", ItemClassification.filler, "any"),
    StagesData(12518, "thorn ms", ItemClassification.filler, "any"),
    StagesData(12526, "poison ms", ItemClassification.filler, "any"),
    StagesData(12555, "explosion ms", ItemClassification.filler, "any"),
    StagesData(12289, "ring", ItemClassification.filler, "any"),
    StagesData(12290, "fire ring", ItemClassification.filler, "any"),
    StagesData(12291, "thunder ring", ItemClassification.filler, "any"),
    StagesData(12292, "long ring", ItemClassification.filler, "any"),
    StagesData(12293, "ice ring", ItemClassification.filler, "any"),
    StagesData(12294, "thorn ring", ItemClassification.filler, "any"),
    StagesData(12295, "power ring", ItemClassification.filler, "any"),
    StagesData(12296, "quick ring", ItemClassification.filler, "any"),
    StagesData(12297, "charge ring", ItemClassification.filler, "any"),
    StagesData(12298, "fire circle", ItemClassification.filler, "any"),
    StagesData(12299, "thunder circle", ItemClassification.filler, "any"),
    StagesData(12300, "long circle", ItemClassification.filler, "any"),
    StagesData(12301, "ice circle", ItemClassification.filler, "any"),
    StagesData(12302, "thorn circle", ItemClassification.filler, "any"),
    StagesData(12303, "power circle", ItemClassification.filler, "any"),
    StagesData(12304, "quick circle", ItemClassification.filler, "any"),
    StagesData(12305, "charge circle", ItemClassification.filler, "any"),
    StagesData(12306, "fire chakram", ItemClassification.filler, "any"),
    StagesData(12307, "chakram", ItemClassification.filler, "any"),
    StagesData(12319, "thunder chakram", ItemClassification.filler, "any"),
    StagesData(12335, "long chakram", ItemClassification.filler, "any"),
    StagesData(12352, "ice chakram", ItemClassification.filler, "any"),
    StagesData(12367, "thorn chakram", ItemClassification.filler, "any"),
    StagesData(12401, "power chakram", ItemClassification.filler, "any"),
    StagesData(12417, "quick chakram", ItemClassification.filler, "any"),
    StagesData(12436, "charge chakram", ItemClassification.filler, "any"),
    StagesData(12458, "fire god", ItemClassification.filler, "any"),
    StagesData(12478, "thunder god", ItemClassification.filler, "any"),
    StagesData(12486, "long god", ItemClassification.filler, "any"),
    StagesData(12503, "ice god", ItemClassification.filler, "any"),
    StagesData(12511, "thorn god", ItemClassification.filler, "any"),
    StagesData(12519, "power god", ItemClassification.filler, "any"),
    StagesData(12527, "quick god", ItemClassification.filler, "any"),
    StagesData(12556, "charge god", ItemClassification.filler, "any"),
    StagesData(12019, "White Stone 1", ItemClassification.filler, "any"),
    StagesData(12084, "White Stone 2", ItemClassification.filler, "any"),
    StagesData(12143, "White Stone 3", ItemClassification.filler, "any"),
    StagesData(12209, "White Stone 4", ItemClassification.filler, "any"),
    StagesData(12323, "White Stone 5", ItemClassification.filler, "any"),
    StagesData(12418, "White Stone 6", ItemClassification.filler, "any"),
    StagesData(12491, "White Stone 7", ItemClassification.filler, "any"),
    StagesData(12020, "Red Stone 1", ItemClassification.filler, "any"),
    StagesData(12085, "Red Stone 2", ItemClassification.filler, "any"),
    StagesData(12144, "Red Stone 3", ItemClassification.filler, "any"),
    StagesData(12210, "Red Stone 4", ItemClassification.filler, "any"),
    StagesData(12324, "Red Stone 5", ItemClassification.filler, "any"),
    StagesData(12419, "Red Stone 6", ItemClassification.filler, "any"),
    StagesData(12492, "Red Stone 7", ItemClassification.filler, "any"),
    StagesData(12021, "Green Stone 1", ItemClassification.filler, "any"),
    StagesData(12086, "Green Stone 2", ItemClassification.filler, "any"),
    StagesData(12145, "Green Stone 3", ItemClassification.filler, "any"),
    StagesData(12211, "Green Stone 4", ItemClassification.filler, "any"),
    StagesData(12325, "Green Stone 5", ItemClassification.filler, "any"),
    StagesData(12420, "Green Stone 6", ItemClassification.filler, "any"),
    StagesData(12493, "Green Stone 7", ItemClassification.filler, "any"),
    StagesData(12022, "Blue Stone 1", ItemClassification.filler, "any"),
    StagesData(12087, "Blue Stone 2", ItemClassification.filler, "any"),
    StagesData(12146, "Blue Stone 3", ItemClassification.filler, "any"),
    StagesData(12212, "Blue Stone 4", ItemClassification.filler, "any"),
    StagesData(12326, "Blue Stone 5", ItemClassification.filler, "any"),
    StagesData(12421, "Blue Stone 6", ItemClassification.filler, "any"),
    StagesData(12494, "Blue Stone 7", ItemClassification.filler, "any"),
    StagesData(12023, "Black Stone 1", ItemClassification.filler, "any"),
    StagesData(12088, "Black Stone 2", ItemClassification.filler, "any"),
    StagesData(12147, "Black Stone 3", ItemClassification.filler, "any"),
    StagesData(12213, "Black Stone 4", ItemClassification.filler, "any"),
    StagesData(12327, "Black Stone 5", ItemClassification.filler, "any"),
    StagesData(12422, "Black Stone 6", ItemClassification.filler, "any"),
    StagesData(12495, "Black Stone 7", ItemClassification.filler, "any"),
    StagesData(12024, "Red Crystal 1", ItemClassification.filler, "any"),
    StagesData(12089, "Red Crystal 2", ItemClassification.filler, "any"),
    StagesData(12148, "Red Crystal 3", ItemClassification.filler, "any"),
    StagesData(12221, "Red Crystal 4", ItemClassification.filler, "any"),
    StagesData(12336, "Red Crystal 5", ItemClassification.filler, "any"),
    StagesData(12424, "Red Crystal 6", ItemClassification.filler, "any"),
    StagesData(12528, "Red Crystal 7", ItemClassification.filler, "any"),
    StagesData(12025, "Yellow Crystal 1", ItemClassification.filler, "any"),
    StagesData(12090, "Yellow Crystal 2", ItemClassification.filler, "any"),
    StagesData(12149, "Yellow Crystal 3", ItemClassification.filler, "any"),
    StagesData(12222, "Yellow Crystal 4", ItemClassification.filler, "any"),
    StagesData(12337, "Yellow Crystal 5", ItemClassification.filler, "any"),
    StagesData(12425, "Yellow Crystal 6", ItemClassification.filler, "any"),
    StagesData(12529, "Yellow Crystal 7", ItemClassification.filler, "any"),
    StagesData(12026, "Silver Crystal 1", ItemClassification.filler, "any"),
    StagesData(12091, "Silver Crystal 2", ItemClassification.filler, "any"),
    StagesData(12150, "Silver Crystal 3", ItemClassification.filler, "any"),
    StagesData(12223, "Silver Crystal 4", ItemClassification.filler, "any"),
    StagesData(12338, "Silver Crystal 5", ItemClassification.filler, "any"),
    StagesData(12426, "Silver Crystal 6", ItemClassification.filler, "any"),
    StagesData(12530, "Silver Crystal 7", ItemClassification.filler, "any"),
    StagesData(12027, "Purple Crystal 1", ItemClassification.filler, "any"),
    StagesData(12092, "Purple Crystal 2", ItemClassification.filler, "any"),
    StagesData(12151, "Purple Crystal 3", ItemClassification.filler, "any"),
    StagesData(12224, "Purple Crystal 4", ItemClassification.filler, "any"),
    StagesData(12339, "Purple Crystal 5", ItemClassification.filler, "any"),
    StagesData(12427, "Purple Crystal 6", ItemClassification.filler, "any"),
    StagesData(12531, "Purple Crystal 7", ItemClassification.filler, "any"),
    StagesData(12028, "Black Crystal 1", ItemClassification.filler, "any"),
    StagesData(12093, "Black Crystal 2", ItemClassification.filler, "any"),
    StagesData(12152, "Black Crystal 3", ItemClassification.filler, "any"),
    StagesData(12225, "Black Crystal 4", ItemClassification.filler, "any"),
    StagesData(12340, "Black Crystal 5", ItemClassification.filler, "any"),
    StagesData(12428, "Black Crystal 6", ItemClassification.filler, "any"),
    StagesData(12532, "Black Crystal 7", ItemClassification.filler, "any"),
    StagesData(12031, "Ruby 1", ItemClassification.filler, "any"),
    StagesData(12096, "Ruby 2", ItemClassification.filler, "any"),
    StagesData(12161, "Ruby 3", ItemClassification.filler, "any"),
    StagesData(12260, "Ruby 4", ItemClassification.filler, "any"),
    StagesData(12369, "Ruby 5", ItemClassification.filler, "any"),
    StagesData(12443, "Ruby 6", ItemClassification.filler, "any"),
    StagesData(12533, "Ruby 7", ItemClassification.filler, "any"),
    StagesData(12032, "Garnet 1", ItemClassification.filler, "any"),
    StagesData(12097, "Garnet 2", ItemClassification.filler, "any"),
    StagesData(12162, "Garnet 3", ItemClassification.filler, "any"),
    StagesData(12261, "Garnet 4", ItemClassification.filler, "any"),
    StagesData(12370, "Garnet 5", ItemClassification.filler, "any"),
    StagesData(12444, "Garnet 6", ItemClassification.filler, "any"),
    StagesData(12534, "Garnet 7", ItemClassification.filler, "any"),
    StagesData(12033, "Sapphire 1", ItemClassification.filler, "any"),
    StagesData(12098, "Sapphire 2", ItemClassification.filler, "any"),
    StagesData(12163, "Sapphire 3", ItemClassification.filler, "any"),
    StagesData(12262, "Sapphire 4", ItemClassification.filler, "any"),
    StagesData(12371, "Sapphire 5", ItemClassification.filler, "any"),
    StagesData(12446, "Sapphire 6", ItemClassification.filler, "any"),
    StagesData(12535, "Sapphire 7", ItemClassification.filler, "any"),
    StagesData(12034, "Aquamarine 1", ItemClassification.filler, "any"),
    StagesData(12099, "Aquamarine 2", ItemClassification.filler, "any"),
    StagesData(12164, "Aquamarine 3", ItemClassification.filler, "any"),
    StagesData(12263, "Aquamarine 4", ItemClassification.filler, "any"),
    StagesData(12372, "Aquamarine 5", ItemClassification.filler, "any"),
    StagesData(12447, "Aquamarine 6", ItemClassification.filler, "any"),
    StagesData(12536, "Aquamarine 7", ItemClassification.filler, "any"),
    StagesData(12035, "Topaz 1", ItemClassification.filler, "any"),
    StagesData(12100, "Topaz 2", ItemClassification.filler, "any"),
    StagesData(12165, "Topaz 3", ItemClassification.filler, "any"),
    StagesData(12264, "Topaz 4", ItemClassification.filler, "any"),
    StagesData(12373, "Topaz 5", ItemClassification.filler, "any"),
    StagesData(12448, "Topaz 6", ItemClassification.filler, "any"),
    StagesData(12537, "Topaz 7", ItemClassification.filler, "any"),
    StagesData(12036, "Emerald 1", ItemClassification.filler, "any"),
    StagesData(12101, "Emerald 2", ItemClassification.filler, "any"),
    StagesData(12166, "Emerald 3", ItemClassification.filler, "any"),
    StagesData(12265, "Emerald 4", ItemClassification.filler, "any"),
    StagesData(12374, "Emerald 5", ItemClassification.filler, "any"),
    StagesData(12449, "Emerald 6", ItemClassification.filler, "any"),
    StagesData(12538, "Emerald 7", ItemClassification.filler, "any"),
    StagesData(12037, "Peridot 1", ItemClassification.filler, "any"),
    StagesData(12102, "Peridot 2", ItemClassification.filler, "any"),
    StagesData(12167, "Peridot 3", ItemClassification.filler, "any"),
    StagesData(12266, "Peridot 4", ItemClassification.filler, "any"),
    StagesData(12375, "Peridot 5", ItemClassification.filler, "any"),
    StagesData(12450, "Peridot 6", ItemClassification.filler, "any"),
    StagesData(12539, "Peridot 7", ItemClassification.filler, "any"),
    StagesData(12038, "Diamond 1", ItemClassification.filler, "any"),
    StagesData(12103, "Diamond 2", ItemClassification.filler, "any"),
    StagesData(12168, "Diamond 3", ItemClassification.filler, "any"),
    StagesData(12267, "Diamond 4", ItemClassification.filler, "any"),
    StagesData(12376, "Diamond 5", ItemClassification.filler, "any"),
    StagesData(12445, "Diamond 6", ItemClassification.filler, "any"),
    StagesData(12540, "Diamond 7", ItemClassification.filler, "any"),
    StagesData(12039, "Quick's Card 1", ItemClassification.filler, "any"),
    StagesData(12104, "Quick's Card 2", ItemClassification.filler, "any"),
    StagesData(12169, "Quick's Card 3", ItemClassification.filler, "any"),
    StagesData(12237, "Quick's Card 4", ItemClassification.filler, "any"),
    StagesData(12353, "Quick's Card 5", ItemClassification.filler, "any"),
    StagesData(12542, "Quick's Card 7", ItemClassification.filler, "any"),
    StagesData(12040, "Long Sword's Card 1", ItemClassification.filler, "any"),
    StagesData(12105, "Long Sword's Card 2", ItemClassification.filler, "any"),
    StagesData(12170, "Long Sword's Card 3", ItemClassification.filler, "any"),
    StagesData(12242, "Long Sword's Card 4", ItemClassification.filler, "any"),
    StagesData(12354, "Long Sword's Card 5", ItemClassification.filler, "any"),
    StagesData(12465, "Long Sword's Card 6", ItemClassification.filler, "any"),
    StagesData(12543, "Long Sword's Card 7", ItemClassification.filler, "any"),
    StagesData(12041, "Catapult's Card 1", ItemClassification.filler, "any"),
    StagesData(12106, "Catapult's Card 2", ItemClassification.filler, "any"),
    StagesData(12171, "Catapult's Card 3", ItemClassification.filler, "any"),
    StagesData(12240, "Catapult's Card 4", ItemClassification.filler, "any"),
    StagesData(12355, "Catapult's Card 5", ItemClassification.filler, "any"),
    StagesData(12466, "Catapult's Card 6", ItemClassification.filler, "any"),
    StagesData(12544, "Catapult's Card 7", ItemClassification.filler, "any"),
    StagesData(12042, "Pierce's Card 1", ItemClassification.filler, "any"),
    StagesData(12107, "Pierce's Card 2", ItemClassification.filler, "any"),
    StagesData(12172, "Pierce's Card 3", ItemClassification.filler, "any"),
    StagesData(12268, "Pierce's Card 4", ItemClassification.filler, "any"),
    StagesData(12043, "Guide's Card 1", ItemClassification.filler, "any"),
    StagesData(12108, "Guide's Card 2", ItemClassification.filler, "any"),
    StagesData(12173, "Guide's Card 3", ItemClassification.filler, "any"),
    StagesData(12269, "Guide's Card 4", ItemClassification.filler, "any"),
    StagesData(12356, "Guide's Card 5", ItemClassification.filler, "any"),
    StagesData(12467, "Guide's Card 6", ItemClassification.filler, "any"),
    StagesData(12545, "Guide's Card 7", ItemClassification.filler, "any"),
    StagesData(12044, "Bullet's Card 1", ItemClassification.filler, "any"),
    StagesData(12109, "Bullet's Card 2", ItemClassification.filler, "any"),
    StagesData(12174, "Bullet's Card 3", ItemClassification.filler, "any"),
    StagesData(12238, "Bullet's Card 4", ItemClassification.filler, "any"),
    StagesData(12357, "Bullet's Card 5", ItemClassification.filler, "any"),
    StagesData(12468, "Bullet's Card 6", ItemClassification.filler, "any"),
    StagesData(12546, "Bullet's Card 7", ItemClassification.filler, "any"),
    StagesData(12045, "Explosion's Card 1", ItemClassification.filler, "any"),
    StagesData(12110, "Explosion's Card 2", ItemClassification.filler, "any"),
    StagesData(12175, "Explosion's Card 3", ItemClassification.filler, "any"),
    StagesData(12249, "Explosion's Card 4", ItemClassification.filler, "any"),
    StagesData(12047, "Critical's Card 1", ItemClassification.filler, "any"),
    StagesData(12111, "Critical's Card 2", ItemClassification.filler, "any"),
    StagesData(12176, "Critical's Card 3", ItemClassification.filler, "any"),
    StagesData(12239, "Critical's Card 4", ItemClassification.filler, "any"),
    StagesData(12358, "Critical's Card 5", ItemClassification.filler, "any"),
    StagesData(12469, "Critical's Card 6", ItemClassification.filler, "any"),
    StagesData(12547, "Critical's Card 7", ItemClassification.filler, "any"),
    StagesData(12046, "Berserk Card 1", ItemClassification.filler, "any"),
    StagesData(12130, "Berserk Card 2", ItemClassification.filler, "any"),
    StagesData(12177, "Berserk Card 3", ItemClassification.filler, "any"),
    StagesData(12241, "Berserk Card 4", ItemClassification.filler, "any"),
    StagesData(12359, "Berserk Card 5", ItemClassification.filler, "any"),
    StagesData(12470, "Berserk Card 6", ItemClassification.filler, "any"),
    StagesData(12548, "Berserk Card 7", ItemClassification.filler, "any"),
    StagesData(12341, "Big Card 1", ItemClassification.filler, "any"),
    StagesData(12342, "Big Card 2", ItemClassification.filler, "any"),
    StagesData(12343, "Big Card 3", ItemClassification.filler, "any"),
    StagesData(12344, "Big Card 4", ItemClassification.filler, "any"),
    StagesData(12368, "Big Card 5", ItemClassification.filler, "any"),
    StagesData(12389, "Knockback's Card 1", ItemClassification.filler, "any"),
    StagesData(12390, "Knockback's Card 2", ItemClassification.filler, "any"),
    StagesData(12391, "Knockback's Card 3", ItemClassification.filler, "any"),
    StagesData(12392, "Knockback's Card 4", ItemClassification.filler, "any"),
    StagesData(12393, "Knockback's Card 5", ItemClassification.filler, "any"),
    StagesData(12406, "Reflection Card 1", ItemClassification.filler, "any"),
    StagesData(12407, "Reflection Card 2", ItemClassification.filler, "any"),
    StagesData(12408, "Reflection Card 3", ItemClassification.filler, "any"),
    StagesData(12409, "Reflection Card 4", ItemClassification.filler, "any"),
    StagesData(12459, "Ring's Card 1", ItemClassification.filler, "any"),
    StagesData(12460, "Ring's Card 2", ItemClassification.filler, "any"),
    StagesData(12461, "Ring's Card 3", ItemClassification.filler, "any"),
    StagesData(12462, "Ring's Card 4", ItemClassification.filler, "any"),
    StagesData(12463, "Ring's Card 5", ItemClassification.filler, "any"),
    StagesData(12464, "Ring's Card 6", ItemClassification.filler, "any"),
    StagesData(12441, "Heal's Card 1", ItemClassification.filler, "any"),
    StagesData(12442, "Heal's Card 2", ItemClassification.filler, "any"),
    StagesData(12541, "Katana's Card 7", ItemClassification.filler, "any"),
    StagesData(12423, "Katana's Card 6", ItemClassification.filler, "any"),
    StagesData(12029, "Vampire's Card 1", ItemClassification.filler, "any"),
    StagesData(12094, "Vampire's Card 3", ItemClassification.filler, "any"),
    StagesData(12159, "Vampire's Card 4", ItemClassification.filler, "any"),
    StagesData(12030, "ONIGIRI's Card", ItemClassification.filler, "any"),
    StagesData(12095, "Gold rush Card", ItemClassification.filler, "any"),
    StagesData(12160, "Zombie's Card", ItemClassification.filler, "any"),
    StagesData(12051, "Bronze Medal 1", ItemClassification.filler, "any"),
    StagesData(12112, "Bronze Medal 2", ItemClassification.filler, "any"),
    StagesData(12184, "Bronze Medal 3", ItemClassification.filler, "any"),
    StagesData(12233, "Bronze Medal 4", ItemClassification.filler, "any"),
    StagesData(12385, "Bronze Medal 5", ItemClassification.filler, "any"),
    StagesData(12437, "Bronze Medal 6", ItemClassification.filler, "any"),
    StagesData(12487, "Bronze Medal 7", ItemClassification.filler, "any"),
    StagesData(12052, "Silver Medal 1", ItemClassification.filler, "any"),
    StagesData(12113, "Silver Medal 2", ItemClassification.filler, "any"),
    StagesData(12185, "Silver Medal 3", ItemClassification.filler, "any"),
    StagesData(12234, "Silver Medal 4", ItemClassification.filler, "any"),
    StagesData(12386, "Silver Medal 5", ItemClassification.filler, "any"),
    StagesData(12438, "Silver Medal 6", ItemClassification.filler, "any"),
    StagesData(12488, "Silver Medal 7", ItemClassification.filler, "any"),
    StagesData(12053, "Gold Medal 1", ItemClassification.filler, "any"),
    StagesData(12114, "Gold Medal 2", ItemClassification.filler, "any"),
    StagesData(12186, "Gold Medal 3", ItemClassification.filler, "any"),
    StagesData(12235, "Gold Medal 4", ItemClassification.filler, "any"),
    StagesData(12387, "Gold Medal 5", ItemClassification.filler, "any"),
    StagesData(12439, "Gold Medal 6", ItemClassification.filler, "any"),
    StagesData(12489, "Gold Medal 7", ItemClassification.filler, "any"),
    StagesData(12048, "Iron Medal 1", ItemClassification.filler, "any"),
    StagesData(12049, "Iron Medal 2", ItemClassification.filler, "any"),
    StagesData(12187, "Iron Medal 3", ItemClassification.filler, "any"),
    StagesData(12236, "Iron Medal 4", ItemClassification.filler, "any"),
    StagesData(12388, "Iron Medal 5", ItemClassification.filler, "any"),
    StagesData(12440, "Iron Medal 6", ItemClassification.filler, "any"),
    StagesData(12490, "Iron Medal 7", ItemClassification.filler, "any"),
    StagesData(12243, "Ice Charm 1", ItemClassification.filler, "any"),
    StagesData(12246, "Ice Charm 2", ItemClassification.filler, "any"),
    StagesData(12250, "Ice Charm 3", ItemClassification.filler, "any"),
    StagesData(12320, "Ice Charm 4", ItemClassification.filler, "any"),
    StagesData(12244, "Poison Charm 1", ItemClassification.filler, "any"),
    StagesData(12247, "Poison Charm 2", ItemClassification.filler, "any"),
    StagesData(12251, "Poison Charm 3", ItemClassification.filler, "any"),
    StagesData(12321, "Poison Charm 4", ItemClassification.filler, "any"),
    StagesData(12245, "Freeze Charm 1", ItemClassification.filler, "any"),
    StagesData(12248, "Freeze Charm 2", ItemClassification.filler, "any"),
    StagesData(12252, "Freeze Charm 3", ItemClassification.filler, "any"),
    StagesData(12322, "Freeze Charm 4", ItemClassification.filler, "any"),
    StagesData(12277, "Fire Spirit 1", ItemClassification.filler, "any"),
    StagesData(12279, "Fire Spirit 2", ItemClassification.filler, "any"),
    StagesData(12281, "Fire Spirit 3", ItemClassification.filler, "any"),
    StagesData(12283, "Fire Spirit 4", ItemClassification.filler, "any"),
    StagesData(12285, "Thunder Spirit 1", ItemClassification.filler, "any"),
    StagesData(12287, "Thunder Spirit 2", ItemClassification.filler, "any"),
    StagesData(12308, "Thunder Spirit 3", ItemClassification.filler, "any"),
    StagesData(12310, "Thunder Spirit 4", ItemClassification.filler, "any"),
    StagesData(12377, "Ice Spirit 1", ItemClassification.filler, "any"),
    StagesData(12379, "Ice Spirit 2", ItemClassification.filler, "any"),
    StagesData(12381, "Ice Spirit 3", ItemClassification.filler, "any"),
    StagesData(12383, "Ice Spirit 4", ItemClassification.filler, "any"),
    StagesData(12404, "Poison Spirit", ItemClassification.filler, "any")
]

traps = [
    TrapItemData(13000, "Unequip items", ItemClassification.trap, 50),
    TrapItemData(13001, "-50% gold", ItemClassification.trap, 10),
    TrapItemData(13002, "Kill a Ranger", ItemClassification.trap, 50),
    TrapItemData(13003, "Freeze Rangers", ItemClassification.trap, 25),
    TrapItemData(13004, "Spawn enemies", ItemClassification.trap, 15),
]

item_list = []
item_list += stages
item_list += levelups
item_list += filler
item_list += traps

item_table = {item.item_name: item for item in item_list}
items_by_id = {item.code: item for item in item_list}

unlocks_by_region: Dict[str, List[str]] = {}
for name, data in item_table.items():
    if data.classification is ItemClassification.progression and name.startswith("Unlock "):
        unlocks_by_region.setdefault(data.region, []).append(name)