from typing import Dict, TypedDict
from BaseClasses import Location

class SRLocation(Location):
    game: str = "Stick Ranger"


class LocationDict(TypedDict, total=False): 
    name: str
    region: str


location_table: Dict[int, LocationDict] = {
    # 10000: {"name": "Town Exit",
    #        "region": "Town"},
    10001: {"name": "Opening Street Exit",
            "region": "Opening Street"},
    10002: {"name": "Grassland 1 Exit",
            "region": "Grassland 1"},
    10003: {"name": "Grassland 2 Exit",
            "region": "Grassland 2"},
    10004: {"name": "Grassland 3 Exit",
            "region": "Grassland 3"},
    10005: {"name": "Grassland 4 Exit",
            "region": "Grassland 4"},
    10006: {"name": "Grassland 5 Exit",
            "region": "Grassland 5"},
    10007: {"name": "Grassland 6 Exit",
            "region": "Grassland 6"},
    10008: {"name": "Grassland 7 Exit",
            "region": "Grassland 7"},
    10009: {"name": "Castle Gate Exit",
            "region": "Castle Gate"},
    10010: {"name": "Castle Exit",
            "region": "Castle"},
    10011: {"name": "Hill Country 1 Exit",
            "region": "Hill Country 1"},
    10012: {"name": "Hill Country 2 Exit",
            "region": "Hill Country 2"},
    10013: {"name": "Hill Country 3 Exit",
            "region": "Hill Country 3"},
    10014: {"name": "Lake Exit",
            "region": "Lake"},
    10015: {"name": "Forest 1 Exit",
            "region": "Forest 1"},
    10016: {"name": "Forest 2 Exit",
            "region": "Forest 2"},
    10017: {"name": "Cavern 1 Exit",
            "region": "Cavern 1"},
    10018: {"name": "Cavern 2 Exit",
            "region": "Cavern 2"},
    10019: {"name": "Cavern 3 Exit",
            "region": "Cavern 3"},
    # 10020: {"name": "Village Exit",
    #        "region": "Village"},
    10021: {"name": "Seaside 1 Exit",
            "region": "Seaside 1"},
    10022: {"name": "Seaside 2 Exit",
            "region": "Seaside 2"},
    10023: {"name": "Seaside 3 Exit",
            "region": "Seaside 3"},
    10024: {"name": "Seaside 4 Exit",
            "region": "Seaside 4"},
    10025: {"name": "Submarine 1 Exit",
            "region": "Submarine 1"},
    10026: {"name": "Submarine 2 Exit",
            "region": "Submarine 2"},
    10027: {"name": "Submarine 3 Exit",
            "region": "Submarine 3"},
    10028: {"name": "Submarine 4 Exit",
            "region": "Submarine 4"},
    10029: {"name": "Submarine Shrine Exit",
            "region": "Submarine Shrine"},
    10030: {"name": "Mist Grove 1 Exit",
            "region": "Mist Grove 1"},
    10031: {"name": "Mist Grove 2 Exit",
            "region": "Mist Grove 2"},
    10032: {"name": "Mist Grove 3 Exit",
            "region": "Mist Grove 3"},
    10033: {"name": "??? Exit",
            "region": "???"},
    10034: {"name": "Desert 1 Exit",
            "region": "Desert 1"},
    10035: {"name": "Desert 2 Exit",
            "region": "Desert 2"},
    10036: {"name": "Desert 3 Exit",
            "region": "Desert 3"},
    10037: {"name": "Desert 4 Exit",
            "region": "Desert 4"},
    10038: {"name": "Desert 5 Exit",
            "region": "Desert 5"},
    10039: {"name": "Oasis Exit",
            "region": "Oasis"},
    10040: {"name": "Desert 6 Exit",
            "region": "Desert 6"},
    10041: {"name": "Desert 7 Exit",
            "region": "Desert 7"},
    10042: {"name": "Pyramid Exit",
            "region": "Pyramid"},
    10043: {"name": "Desert 8 Exit",
            "region": "Desert 8"},
    10044: {"name": "Beach 1 Exit",
            "region": "Beach 1"},
    10045: {"name": "Beach 2 Exit",
            "region": "Beach 2"},
    10046: {"name": "Beach 3 Exit",
            "region": "Beach 3"},
    # 10047: {"name": "Resort Exit",
    #        "region": "Resort"},
    10048: {"name": "Cavern 4 Exit",
            "region": "Cavern 4"},
    10049: {"name": "Cavern 5 Exit",
            "region": "Cavern 5"},
    10050: {"name": "Cavern 6 Exit",
            "region": "Cavern 6"},
    10051: {"name": "Snowfield 1 Exit",
            "region": "Snowfield 1"},
    10052: {"name": "Snowfield 2 Exit",
            "region": "Snowfield 2"},
    10053: {"name": "Mountain 1 Exit",
            "region": "Mountain 1"},
    10054: {"name": "Mountain 2 Exit",
            "region": "Mountain 2"},
    10055: {"name": "Mountaintop Exit",
            "region": "Mountaintop"},
    10056: {"name": "Snowfield 3 Exit",
            "region": "Snowfield 3"},
    10057: {"name": "Snowfield 4 Exit",
            "region": "Snowfield 4"},
    10058: {"name": "Snowfield 5 Exit",
            "region": "Snowfield 5"},
    10059: {"name": "Snowfield 6 Exit",
            "region": "Snowfield 6"},
    10060: {"name": "Snowfield 7 Exit",
            "region": "Snowfield 7"},
    10061: {"name": "Snowfield 8 Exit",
            "region": "Snowfield 8"},
    10062: {"name": "Frozen Lake Exit",
            "region": "Frozen Lake"},
    10063: {"name": "Ice Castle Exit",
            "region": "Ice Castle"},
    10064: {"name": "Snowfield 9 Exit",
            "region": "Snowfield 9"},
    10065: {"name": "Beach 4 Exit",
            "region": "Beach 4"},
    10066: {"name": "Forest 3 Exit",
            "region": "Forest 3"},
    10067: {"name": "Forest 4 Exit",
            "region": "Forest 4"},
    10068: {"name": "Forest 5 Exit",
            "region": "Forest 5"},
    10069: {"name": "Forest 6 Exit",
            "region": "Forest 6"},
    # 10070: {"name": "Forget Tree Exit",
    #        "region": "Forget Tree"},
    10071: {"name": "!!! Exit",
            "region": "!!!"},
    10072: {"name": "Hell 1 Exit",
            "region": "Hell 1"},
    10073: {"name": "Hell 2 Exit",
            "region": "Hell 2"},
    10074: {"name": "Hell 3 Exit",
            "region": "Hell 3"},
    10075: {"name": "Hell 4 Exit",
            "region": "Hell 4"},
    10076: {"name": "Hell 5 Exit",
            "region": "Hell 5"},
    # 10077: {"name": "Island Exit",
    #        "region": "Island"},
    10078: {"name": "Hell 6 Exit",
            "region": "Hell 6"},
    10079: {"name": "Inferno 1 Exit",
            "region": "Inferno 1"},
    10080: {"name": "Inferno 2 Exit",
            "region": "Inferno 2"},
    10081: {"name": "Inferno 3 Exit",
            "region": "Inferno 3"},
    10082: {"name": "Blood Lake Exit",
            "region": "Blood Lake"},
    10083: {"name": "Cavern 7 Exit",
            "region": "Cavern 7"},
    10084: {"name": "Cavern 8 Exit",
            "region": "Cavern 8"},
    10085: {"name": "Hell 7 Exit",
            "region": "Hell 7"},
    10086: {"name": "Hell 8 Exit",
            "region": "Hell 8"},
    10087: {"name": "Hell Gate Exit",
            "region": "Hell Gate"},
    10088: {"name": "Hell Castle Exit",
            "region": "Hell Castle"},
    10089: {"name": "Volcano Exit",
            "region": "Volcano"},
    # 10100: {"name": "Town Book",
    #        "region": "Town"},
    10101: {"name": "Opening Street Book",
            "region": "Opening Street"},
    10102: {"name": "Grassland 1 Book",
            "region": "Grassland 1"},
    10103: {"name": "Grassland 2 Book",
            "region": "Grassland 2"},
    10104: {"name": "Grassland 3 Book",
            "region": "Grassland 3"},
    10105: {"name": "Grassland 4 Book",
            "region": "Grassland 4"},
    10106: {"name": "Grassland 5 Book",
            "region": "Grassland 5"},
    10107: {"name": "Grassland 6 Book",
            "region": "Grassland 6"},
    10108: {"name": "Grassland 7 Book",
            "region": "Grassland 7"},
    10109: {"name": "Castle Gate Book",
            "region": "Castle Gate"},
    10110: {"name": "Castle Book",
            "region": "Castle"},
    10111: {"name": "Hill Country 1 Book",
            "region": "Hill Country 1"},
    10112: {"name": "Hill Country 2 Book",
            "region": "Hill Country 2"},
    10113: {"name": "Hill Country 3 Book",
            "region": "Hill Country 3"},
    10114: {"name": "Lake Book",
            "region": "Lake"},
    10115: {"name": "Forest 1 Book",
            "region": "Forest 1"},
    10116: {"name": "Forest 2 Book",
            "region": "Forest 2"},
    10117: {"name": "Cavern 1 Book",
            "region": "Cavern 1"},
    10118: {"name": "Cavern 2 Book",
            "region": "Cavern 2"},
    10119: {"name": "Cavern 3 Book",
            "region": "Cavern 3"},
    # 10120: {"name": "Village Book",
    #        "region": "Village"},
    10121: {"name": "Seaside 1 Book",
            "region": "Seaside 1"},
    10122: {"name": "Seaside 2 Book",
            "region": "Seaside 2"},
    10123: {"name": "Seaside 3 Book",
            "region": "Seaside 3"},
    10124: {"name": "Seaside 4 Book",
            "region": "Seaside 4"},
    10125: {"name": "Submarine 1 Book",
            "region": "Submarine 1"},
    10126: {"name": "Submarine 2 Book",
            "region": "Submarine 2"},
    10127: {"name": "Submarine 3 Book",
            "region": "Submarine 3"},
    10128: {"name": "Submarine 4 Book",
            "region": "Submarine 4"},
    10129: {"name": "Submarine Shrine Book",
            "region": "Submarine Shrine"},
    10130: {"name": "Mist Grove 1 Book",
            "region": "Mist Grove 1"},
    10131: {"name": "Mist Grove 2 Book",
            "region": "Mist Grove 2"},
    10132: {"name": "Mist Grove 3 Book",
            "region": "Mist Grove 3"},
    10133: {"name": "??? Book",
            "region": "???"},
    10134: {"name": "Desert 1 Book",
            "region": "Desert 1"},
    10135: {"name": "Desert 2 Book",
            "region": "Desert 2"},
    10136: {"name": "Desert 3 Book",
            "region": "Desert 3"},
    10137: {"name": "Desert 4 Book",
            "region": "Desert 4"},
    10138: {"name": "Desert 5 Book",
            "region": "Desert 5"},
    10139: {"name": "Oasis Book",
            "region": "Oasis"},
    10140: {"name": "Desert 6 Book",
            "region": "Desert 6"},
    10141: {"name": "Desert 7 Book",
            "region": "Desert 7"},
    10142: {"name": "Pyramid Book",
            "region": "Pyramid"},
    10143: {"name": "Desert 8 Book",
            "region": "Desert 8"},
    10144: {"name": "Beach 1 Book",
            "region": "Beach 1"},
    10145: {"name": "Beach 2 Book",
            "region": "Beach 2"},
    10146: {"name": "Beach 3 Book",
            "region": "Beach 3"},
    # 10147: {"name": "Resort Book",
    #        "region": "Resort"},
    10148: {"name": "Cavern 4 Book",
            "region": "Cavern 4"},
    10149: {"name": "Cavern 5 Book",
            "region": "Cavern 5"},
    10150: {"name": "Cavern 6 Book",
            "region": "Cavern 6"},
    10151: {"name": "Snowfield 1 Book",
            "region": "Snowfield 1"},
    10152: {"name": "Snowfield 2 Book",
            "region": "Snowfield 2"},
    10153: {"name": "Mountain 1 Book",
            "region": "Mountain 1"},
    10154: {"name": "Mountain 2 Book",
            "region": "Mountain 2"},
    10155: {"name": "Mountaintop Book",
            "region": "Mountaintop"},
    10156: {"name": "Snowfield 3 Book",
            "region": "Snowfield 3"},
    10157: {"name": "Snowfield 4 Book",
            "region": "Snowfield 4"},
    10158: {"name": "Snowfield 5 Book",
            "region": "Snowfield 5"},
    10159: {"name": "Snowfield 6 Book",
            "region": "Snowfield 6"},
    10160: {"name": "Snowfield 7 Book",
            "region": "Snowfield 7"},
    10161: {"name": "Snowfield 8 Book",
            "region": "Snowfield 8"},
    10162: {"name": "Frozen Lake Book",
            "region": "Frozen Lake"},
    10163: {"name": "Ice Castle Book",
            "region": "Ice Castle"},
    10164: {"name": "Snowfield 9 Book",
            "region": "Snowfield 9"},
    10165: {"name": "Beach 4 Book",
            "region": "Beach 4"},
    10166: {"name": "Forest 3 Book",
            "region": "Forest 3"},
    10167: {"name": "Forest 4 Book",
            "region": "Forest 4"},
    10168: {"name": "Forest 5 Book",
            "region": "Forest 5"},
    10169: {"name": "Forest 6 Book",
            "region": "Forest 6"},
    # 10170: {"name": "Forget Tree Book",
    #        "region": "Forget Tree"},
    10171: {"name": "!!! Book",
            "region": "!!!"},
    10172: {"name": "Hell 1 Book",
            "region": "Hell 1"},
    10173: {"name": "Hell 2 Book",
            "region": "Hell 2"},
    10174: {"name": "Hell 3 Book",
            "region": "Hell 3"},
    10175: {"name": "Hell 4 Book",
            "region": "Hell 4"},
    10176: {"name": "Hell 5 Book",
            "region": "Hell 5"},
    # 10177: {"name": "Island Book",
    #        "region": "Island"},
    10178: {"name": "Hell 6 Book",
            "region": "Hell 6"},
    10179: {"name": "Inferno 1 Book",
            "region": "Inferno 1"},
    10180: {"name": "Inferno 2 Book",
            "region": "Inferno 2"},
    10181: {"name": "Inferno 3 Book",
            "region": "Inferno 3"},
    10182: {"name": "Blood Lake Book",
            "region": "Blood Lake"},
    10183: {"name": "Cavern 7 Book",
            "region": "Cavern 7"},
    10184: {"name": "Cavern 8 Book",
            "region": "Cavern 8"},
    10185: {"name": "Hell 7 Book",
            "region": "Hell 7"},
    10186: {"name": "Hell 8 Book",
            "region": "Hell 8"},
    10187: {"name": "Hell Gate Book",
            "region": "Hell Gate"},
    10188: {"name": "Hell Castle Book",
            "region": "Hell Castle"},
    10189: {"name": "Volcano Book",
            "region": "Volcano"}
}

location_name_to_id = {
    value['name']: id
    for id, value in location_table.items()
}

lookup_id_to_name: Dict[int, str] = {
    data: item_name for item_name, data in location_name_to_id.items() if data
}
