from typing import Dict, TypedDict
from BaseClasses import Location


class SRLocation(Location):
    game: str = "Stick Ranger"


class LocationDict(TypedDict, total=False):
    name: str
    region: str

stages_table: Dict[int, LocationDict] = {
   #10000: {"name": "Town Exit", "region": "Town"},
    10001: {"name": "Opening Street Exit", "region": "Opening Street"},
    10002: {"name": "Grassland 1 Exit", "region": "Grassland 1"},
    10003: {"name": "Grassland 2 Exit", "region": "Grassland 2"},
    10004: {"name": "Grassland 3 Exit", "region": "Grassland 3"},
    10005: {"name": "Grassland 4 Exit", "region": "Grassland 4"},
    10006: {"name": "Grassland 5 Exit", "region": "Grassland 5"},
    10007: {"name": "Grassland 6 Exit", "region": "Grassland 6"},
    10008: {"name": "Grassland 7 Exit", "region": "Grassland 7"},
    10009: {"name": "Castle Gate Exit", "region": "Castle Gate"},
    10010: {"name": "Castle Exit", "region": "Castle"},
    10011: {"name": "Hill Country 1 Exit", "region": "Hill Country 1"},
    10012: {"name": "Hill Country 2 Exit", "region": "Hill Country 2"},
    10013: {"name": "Hill Country 3 Exit", "region": "Hill Country 3"},
    10014: {"name": "Lake Exit", "region": "Lake"},
    10015: {"name": "Forest 1 Exit", "region": "Forest 1"},
    10016: {"name": "Forest 2 Exit", "region": "Forest 2"},
    10017: {"name": "Cavern 1 Exit", "region": "Cavern 1"},
    10018: {"name": "Cavern 2 Exit", "region": "Cavern 2"},
    10019: {"name": "Cavern 3 Exit", "region": "Cavern 3"},
   #10020: {"name": "Village Exit", "region": "Village"},
    10021: {"name": "Seaside 1 Exit", "region": "Seaside 1"},
    10022: {"name": "Seaside 2 Exit", "region": "Seaside 2"},
    10023: {"name": "Seaside 3 Exit", "region": "Seaside 3"},
    10024: {"name": "Seaside 4 Exit", "region": "Seaside 4"},
    10025: {"name": "Submarine 1 Exit", "region": "Submarine 1"},
    10026: {"name": "Submarine 2 Exit", "region": "Submarine 2"},
    10027: {"name": "Submarine 3 Exit", "region": "Submarine 3"},
    10028: {"name": "Submarine 4 Exit", "region": "Submarine 4"},
    10029: {"name": "Submarine Shrine Exit", "region": "Submarine Shrine"},
    10030: {"name": "Mist Grove 1 Exit", "region": "Mist Grove 1"},
    10031: {"name": "Mist Grove 2 Exit", "region": "Mist Grove 2"},
    10032: {"name": "Mist Grove 3 Exit", "region": "Mist Grove 3"},
    10033: {"name": "??? Exit", "region": "???"},
    10034: {"name": "Desert 1 Exit", "region": "Desert 1"},
    10035: {"name": "Desert 2 Exit", "region": "Desert 2"},
    10036: {"name": "Desert 3 Exit", "region": "Desert 3"},
    10037: {"name": "Desert 4 Exit", "region": "Desert 4"},
    10038: {"name": "Desert 5 Exit", "region": "Desert 5"},
    10039: {"name": "Oasis Exit", "region": "Oasis"},
    10040: {"name": "Desert 6 Exit", "region": "Desert 6"},
    10041: {"name": "Desert 7 Exit", "region": "Desert 7"},
    10042: {"name": "Pyramid Exit", "region": "Pyramid"},
    10043: {"name": "Desert 8 Exit", "region": "Desert 8"},
    10044: {"name": "Beach 1 Exit", "region": "Beach 1"},
    10045: {"name": "Beach 2 Exit", "region": "Beach 2"},
    10046: {"name": "Beach 3 Exit", "region": "Beach 3"},
   #10047: {"name": "Resort Exit", "region": "Resort"},
    10048: {"name": "Cavern 4 Exit", "region": "Cavern 4"},
    10049: {"name": "Cavern 5 Exit", "region": "Cavern 5"},
    10050: {"name": "Cavern 6 Exit", "region": "Cavern 6"},
    10051: {"name": "Snowfield 1 Exit", "region": "Snowfield 1"},
    10052: {"name": "Snowfield 2 Exit", "region": "Snowfield 2"},
    10053: {"name": "Mountain 1 Exit", "region": "Mountain 1"},
    10054: {"name": "Mountain 2 Exit", "region": "Mountain 2"},
    10055: {"name": "Mountaintop Exit", "region": "Mountaintop"},
    10056: {"name": "Snowfield 3 Exit", "region": "Snowfield 3"},
    10057: {"name": "Snowfield 4 Exit", "region": "Snowfield 4"},
    10058: {"name": "Snowfield 5 Exit", "region": "Snowfield 5"},
    10059: {"name": "Snowfield 6 Exit", "region": "Snowfield 6"},
    10060: {"name": "Snowfield 7 Exit", "region": "Snowfield 7"},
    10061: {"name": "Snowfield 8 Exit", "region": "Snowfield 8"},
    10062: {"name": "Frozen Lake Exit", "region": "Frozen Lake"},
    10063: {"name": "Ice Castle Exit", "region": "Ice Castle"},
    10064: {"name": "Snowfield 9 Exit", "region": "Snowfield 9"},
    10065: {"name": "Beach 4 Exit", "region": "Beach 4"},
    10066: {"name": "Forest 3 Exit", "region": "Forest 3"},
    10067: {"name": "Forest 4 Exit", "region": "Forest 4"},
    10068: {"name": "Forest 5 Exit", "region": "Forest 5"},
    10069: {"name": "Forest 6 Exit", "region": "Forest 6"},
   #10070: {"name": "Forget Tree Exit", "region": "Forget Tree"},
    10071: {"name": "!!! Exit", "region": "!!!"},
    10072: {"name": "Hell 1 Exit", "region": "Hell 1"},
    10073: {"name": "Hell 2 Exit", "region": "Hell 2"},
    10074: {"name": "Hell 3 Exit", "region": "Hell 3"},
    10075: {"name": "Hell 4 Exit", "region": "Hell 4"},
    10076: {"name": "Hell 5 Exit", "region": "Hell 5"},
   #10077: {"name": "Island Exit", "region": "Island"},
    10078: {"name": "Hell 6 Exit", "region": "Hell 6"},
    10079: {"name": "Inferno 1 Exit", "region": "Inferno 1"},
    10080: {"name": "Inferno 2 Exit", "region": "Inferno 2"},
    10081: {"name": "Inferno 3 Exit", "region": "Inferno 3"},
    10082: {"name": "Blood Lake Exit", "region": "Blood Lake"},
    10083: {"name": "Cavern 7 Exit", "region": "Cavern 7"},
    10084: {"name": "Cavern 8 Exit", "region": "Cavern 8"},
    10085: {"name": "Hell 7 Exit", "region": "Hell 7"},
    10086: {"name": "Hell 8 Exit", "region": "Hell 8"},
    10087: {"name": "Hell Gate Exit", "region": "Hell Gate"},
    10088: {"name": "Hell Castle Exit", "region": "Hell Castle"},
    10089: {"name": "Volcano Exit", "region": "Volcano"},
}

books_table: Dict[int, LocationDict] = {
   #10100: {"name": "Town Book", "region": "Town"},
    10101: {"name": "Opening Street Book", "region": "Opening Street"},
    10102: {"name": "Grassland 1 Book", "region": "Grassland 1"},
    10103: {"name": "Grassland 2 Book", "region": "Grassland 2"},
    10104: {"name": "Grassland 3 Book", "region": "Grassland 3"},
    10105: {"name": "Grassland 4 Book", "region": "Grassland 4"},
    10106: {"name": "Grassland 5 Book", "region": "Grassland 5"},
    10107: {"name": "Grassland 6 Book", "region": "Grassland 6"},
    10108: {"name": "Grassland 7 Book", "region": "Grassland 7"},
    10109: {"name": "Castle Gate Book", "region": "Castle Gate"},
    10110: {"name": "Castle Book", "region": "Castle"},
    10111: {"name": "Hill Country 1 Book", "region": "Hill Country 1"},
    10112: {"name": "Hill Country 2 Book", "region": "Hill Country 2"},
    10113: {"name": "Hill Country 3 Book", "region": "Hill Country 3"},
    10114: {"name": "Lake Book", "region": "Lake"},
    10115: {"name": "Forest 1 Book", "region": "Forest 1"},
    10116: {"name": "Forest 2 Book", "region": "Forest 2"},
    10117: {"name": "Cavern 1 Book", "region": "Cavern 1"},
    10118: {"name": "Cavern 2 Book", "region": "Cavern 2"},
    10119: {"name": "Cavern 3 Book", "region": "Cavern 3"},
   #10120: {"name": "Village Book", "region": "Village"},
    10121: {"name": "Seaside 1 Book", "region": "Seaside 1"},
    10122: {"name": "Seaside 2 Book", "region": "Seaside 2"},
    10123: {"name": "Seaside 3 Book", "region": "Seaside 3"},
    10124: {"name": "Seaside 4 Book", "region": "Seaside 4"},
    10125: {"name": "Submarine 1 Book", "region": "Submarine 1"},
    10126: {"name": "Submarine 2 Book", "region": "Submarine 2"},
    10127: {"name": "Submarine 3 Book", "region": "Submarine 3"},
    10128: {"name": "Submarine 4 Book", "region": "Submarine 4"},
    10129: {"name": "Submarine Shrine Book", "region": "Submarine Shrine"},
    10130: {"name": "Mist Grove 1 Book", "region": "Mist Grove 1"},
    10131: {"name": "Mist Grove 2 Book", "region": "Mist Grove 2"},
    10132: {"name": "Mist Grove 3 Book", "region": "Mist Grove 3"},
    10133: {"name": "??? Book", "region": "???"},
    10134: {"name": "Desert 1 Book", "region": "Desert 1"},
    10135: {"name": "Desert 2 Book", "region": "Desert 2"},
    10136: {"name": "Desert 3 Book", "region": "Desert 3"},
    10137: {"name": "Desert 4 Book", "region": "Desert 4"},
    10138: {"name": "Desert 5 Book", "region": "Desert 5"},
    10139: {"name": "Oasis Book", "region": "Oasis"},
    10140: {"name": "Desert 6 Book", "region": "Desert 6"},
    10141: {"name": "Desert 7 Book", "region": "Desert 7"},
    10142: {"name": "Pyramid Book", "region": "Pyramid"},
    10143: {"name": "Desert 8 Book", "region": "Desert 8"},
    10144: {"name": "Beach 1 Book", "region": "Beach 1"},
    10145: {"name": "Beach 2 Book", "region": "Beach 2"},
    10146: {"name": "Beach 3 Book", "region": "Beach 3"},
   #10147: {"name": "Resort Book", "region": "Resort"},
    10148: {"name": "Cavern 4 Book", "region": "Cavern 4"},
    10149: {"name": "Cavern 5 Book", "region": "Cavern 5"},
    10150: {"name": "Cavern 6 Book", "region": "Cavern 6"},
    10151: {"name": "Snowfield 1 Book", "region": "Snowfield 1"},
    10152: {"name": "Snowfield 2 Book", "region": "Snowfield 2"},
    10153: {"name": "Mountain 1 Book", "region": "Mountain 1"},
    10154: {"name": "Mountain 2 Book", "region": "Mountain 2"},
    10155: {"name": "Mountaintop Book", "region": "Mountaintop"},
    10156: {"name": "Snowfield 3 Book", "region": "Snowfield 3"},
    10157: {"name": "Snowfield 4 Book", "region": "Snowfield 4"},
    10158: {"name": "Snowfield 5 Book", "region": "Snowfield 5"},
    10159: {"name": "Snowfield 6 Book", "region": "Snowfield 6"},
    10160: {"name": "Snowfield 7 Book", "region": "Snowfield 7"},
    10161: {"name": "Snowfield 8 Book", "region": "Snowfield 8"},
    10162: {"name": "Frozen Lake Book", "region": "Frozen Lake"},
    10163: {"name": "Ice Castle Book", "region": "Ice Castle"},
    10164: {"name": "Snowfield 9 Book", "region": "Snowfield 9"},
    10165: {"name": "Beach 4 Book", "region": "Beach 4"},
    10166: {"name": "Forest 3 Book", "region": "Forest 3"},
    10167: {"name": "Forest 4 Book", "region": "Forest 4"},
    10168: {"name": "Forest 5 Book", "region": "Forest 5"},
    10169: {"name": "Forest 6 Book", "region": "Forest 6"},
   #10170: {"name": "Forget Tree Book", "region": "Forget Tree"},
    10171: {"name": "!!! Book", "region": "!!!"},
    10172: {"name": "Hell 1 Book", "region": "Hell 1"},
    10173: {"name": "Hell 2 Book", "region": "Hell 2"},
    10174: {"name": "Hell 3 Book", "region": "Hell 3"},
    10175: {"name": "Hell 4 Book", "region": "Hell 4"},
    10176: {"name": "Hell 5 Book", "region": "Hell 5"},
   #10177: {"name": "Island Book", "region": "Island"},
    10178: {"name": "Hell 6 Book", "region": "Hell 6"},
    10179: {"name": "Inferno 1 Book", "region": "Inferno 1"},
    10180: {"name": "Inferno 2 Book", "region": "Inferno 2"},
    10181: {"name": "Inferno 3 Book", "region": "Inferno 3"},
    10182: {"name": "Blood Lake Book", "region": "Blood Lake"},
    10183: {"name": "Cavern 7 Book", "region": "Cavern 7"},
    10184: {"name": "Cavern 8 Book", "region": "Cavern 8"},
    10185: {"name": "Hell 7 Book", "region": "Hell 7"},
    10186: {"name": "Hell 8 Book", "region": "Hell 8"},
    10187: {"name": "Hell Gate Book", "region": "Hell Gate"},
    10188: {"name": "Hell Castle Book", "region": "Hell Castle"},
    10189: {"name": "Volcano Book", "region": "Volcano"},
}

enemies_table: Dict[int, LocationDict] = {
    10200: {"name": "Green Smiley Walker (Opening Street)", "region": "Opening Street"},
    10201: {"name": "Cyan Smiley Walker", "region": "Opening Street"},
    10202: {"name": "Red Smiley Walker", "region": "Opening Street"},
    10203: {"name": "Blue X Walker", "region": "Opening Street"},
    10204: {"name": "Grey Boss Smiley Walker", "region": "Opening Street"},
    10205: {"name": "Green Skull Snake", "region": "Grassland 1"},
    10206: {"name": "Grey Smiley Snake", "region": "Grassland 1"},
    10207: {"name": "Red Skull Snake (Grassland 1)", "region": "Grassland 1"},
    10208: {"name": "Green Boss Skull Snake", "region": "Grassland 1"},
    10209: {"name": "White Skull Bat (Grassland 2)", "region": "Grassland 2"},
    10210: {"name": "Orange Smiley Walker (Grassland 2)", "region": "Grassland 2"},
    10211: {"name": "Purple X Walker", "region": "Grassland 2"},
    10212: {"name": "Orange Skull Bat (Grassland 2)", "region": "Grassland 2"},
    10213: {"name": "Grey Boss Skull Bat", "region": "Grassland 2"},
    10214: {"name": "Green Skull Dragon", "region": "Grassland 3"},
    10215: {"name": "Green Smiley Snake", "region": "Grassland 3"},
    10216: {"name": "Green Skull Bat", "region": "Grassland 3"},
    10217: {"name": "Red Big Skull Dragon", "region": "Grassland 3"},
    10218: {"name": "Orange Boss Skull Dragon", "region": "Grassland 3"},
    10219: {"name": "Blue Fairy Snake", "region": "Grassland 4"},
    10220: {"name": "Grey X Walker (Grassland 4)", "region": "Grassland 4"},
    10221: {"name": "Red Fairy Snake", "region": "Grassland 4"},
    10222: {"name": "Blue Boss Fairy Snake", "region": "Grassland 4"},
    10223: {"name": "Green Smiley Tree", "region": "Grassland 5"},
    10224: {"name": "Pink Skull Snake", "region": "Grassland 5"},
    10225: {"name": "Orange Smiley Tree", "region": "Grassland 5"},
    10226: {"name": "Red Boss Smiley Tree", "region": "Grassland 5"},
    10227: {"name": "Grey Smiley Tree", "region": "Grassland 6"},
    10228: {"name": "Green Fairy Bat", "region": "Grassland 6"},
    10229: {"name": "Orange Fairy Bat", "region": "Grassland 6"},
    10230: {"name": "Purple Boss Smiley Tree", "region": "Grassland 6"},
    10231: {"name": "Grey Smiley Tree", "region": "Grassland 7"},
    10232: {"name": "Green Smiley Wheel", "region": "Grassland 7"},
    10233: {"name": "Yellow Smiley Wheel", "region": "Grassland 7"},
    10234: {"name": "Orange Boss Smiley Wheel", "region": "Grassland 7"},
    10235: {"name": "White Skull Stickman (Castle Gate)", "region": "Castle Gate"},
    10236: {"name": "Red Skull Stickman (Castle Gate)", "region": "Castle Gate"},
    10237: {"name": "Orange Smiley Wheel", "region": "Castle Gate"},
    10238: {"name": "White Boss Skull Stickman (Castle Gate)", "region": "Castle Gate"},
    10239: {"name": "Castle Boss", "region": "Castle"},
   #10240 Castle Boss attack id
    10241: {"name": "Green Big Smiley Walker", "region": "Hill Country 1"},
    10242: {"name": "Green Smiley Walker (Hill Country 1)", "region": "Hill Country 1"},
    10243: {"name": "Brown X Walker", "region": "Hill Country 1"},
    10244: {"name": "White Boss X Walker (Hill Country 1)", "region": "Hill Country 1"},
    10245: {"name": "Blue Big Skull Bat", "region": "Hill Country 2"},
    10246: {"name": "Blue Skull Bat (Hill Country 2)", "region": "Hill Country 2"},
    10247: {"name": "Green Skull Tree", "region": "Hill Country 2"},
    10248: {"name": "Orange Boss Skull Bat", "region": "Hill Country 2"},
    10249: {"name": "Green Big Smiley Snake", "region": "Hill Country 3"},
    10250: {"name": "Green Big Fairy Snake", "region": "Hill Country 3"},
    10251: {"name": "Pink Skull Tree (Hill Country 3)", "region": "Hill Country 3"},
    10252: {"name": "White Boss Smiley Snake", "region": "Hill Country 3"},
    10253: {"name": "Tan Skull Fish", "region": "Lake"},
    10254: {"name": "Pink Skull Tree (Lake)", "region": "Lake"},
    10255: {"name": "Green Smiley Fish", "region": "Lake"},
    10256: {"name": "White Boss Smiley Fish", "region": "Lake"},
    10257: {"name": "Tan Skull Snake", "region": "Forest 1"},
    10258: {"name": "Green Cap Mushroom", "region": "Forest 1"},
    10259: {"name": "Red Skull Snake (Forest 1)", "region": "Forest 1"},
    10260: {"name": "Green Boss Cap Mushroom", "region": "Forest 1"},
    10261: {"name": "Tan Skull Bat", "region": "Forest 2"},
    10262: {"name": "Purple Cap Mushroom", "region": "Forest 2"},
    10263: {"name": "Red Skull Bat", "region": "Forest 2"},
    10264: {"name": "Purple Boss Cap Mushroom", "region": "Forest 2"},
    10265: {"name": "Orange Smiley Walker (Cavern 1)", "region": "Cavern 1"},
    10266: {"name": "Green Cap Snake", "region": "Cavern 1"},
    10267: {"name": "Red Cap Snake", "region": "Cavern 1"},
    10268: {"name": "White Boss Smiley Walker", "region": "Cavern 1"},
    10269: {"name": "Yellow Skull Fish", "region": "Cavern 1"},
    10270: {"name": "Blue Skull Bat (Cavern 2)", "region": "Cavern 2"},
    10271: {"name": "Purple Skull Bat", "region": "Cavern 2"},
    10272: {"name": "Pink Fairy Bat", "region": "Cavern 2"},
    10273: {"name": "White Boss Skull Bat", "region": "Cavern 2"},
    10274: {"name": "Yellow Smiley Fish", "region": "Cavern 2"},
    10275: {"name": "Yellow Skull Stickman", "region": "Cavern 3"},
    10276: {"name": "Orange Skull Bat (Cavern 3)", "region": "Cavern 3"},
    10277: {"name": "Orange Skull Stickman", "region": "Cavern 3"},
    10278: {"name": "Orange Boss Skull Stickman", "region": "Cavern 3"},
    10279: {"name": "Yellow Fairy Fish", "region": "Cavern 3"},
    10280: {"name": "Green Roundhead Walker", "region": "Seaside 1"},
    10281: {"name": "Cyan Roundhead Walker", "region": "Seaside 1"},
    10282: {"name": "Red Roundhead Walker", "region": "Seaside 1"},
    10283: {"name": "Blue Roundhead Tree", "region": "Seaside 1"},
    10284: {"name": "Grey Boss Roundhead Walker", "region": "Seaside 1"},
    10285: {"name": "White Roundhead Snake (Seaside 2)", "region": "Seaside 2"},
    10286: {"name": "Red Roundhead Snake", "region": "Seaside 2"},
    10287: {"name": "White Roundhead Bat", "region": "Seaside 2"},
    10288: {"name": "Red Roundhead Bat", "region": "Seaside 2"},
    10289: {"name": "Grey Boss Roundhead Snake", "region": "Seaside 2"},
    10290: {"name": "Cyan Gel Snake", "region": "Seaside 3"},
    10291: {"name": "Cyan Gel Dragon", "region": "Seaside 3"},
    10292: {"name": "Pink Gel Tree (Seaside 3)", "region": "Seaside 3"},
    10293: {"name": "Cyan Boss Gel Dragon", "region": "Seaside 3"},
    10294: {"name": "Green Gel Walker", "region": "Seaside 4"},
    10295: {"name": "Green Roundhead Bat", "region": "Seaside 4"},
    10296: {"name": "Tan Star Stickman", "region": "Seaside 4"},
    10297: {"name": "Tan Boss Star Stickman", "region": "Seaside 4"},
    10298: {"name": "White Roundhead Fish", "region": "Submarine 1"},
    10299: {"name": "Pink Roundhead Eel", "region": "Submarine 1"},
    10300: {"name": "Pink Gel Eel", "region": "Submarine 1"},
    10301: {"name": "Tan Boss Roundhead Eel", "region": "Submarine 1"},
    10302: {"name": "Green Gel Tree", "region": "Submarine 2"},
    10303: {"name": "Pink Roundhead Fish", "region": "Submarine 2"},
    10304: {"name": "Pink Gel Walker", "region": "Submarine 2"},
    10305: {"name": "Red Boss Gel Tree (Submarine 2)", "region": "Submarine 2"},
    10306: {"name": "Blue Roundhead Fish", "region": "Submarine 3"},
    10307: {"name": "Grey Smiley Fish", "region": "Submarine 3"},
    10308: {"name": "Orange Mask Eel", "region": "Submarine 3"},
    10309: {"name": "Blue Boss Roundhead Eel", "region": "Submarine 3"},
    10310: {"name": "Yellow Roundhead Fish", "region": "Submarine 4"},
    10311: {"name": "Grey Mask Fish", "region": "Submarine 4"},
    10312: {"name": "Grey Big Mask Fish", "region": "Submarine 4"},
    10313: {"name": "Grey Boss Mask Fish", "region": "Submarine 4"},
    10314: {"name": "Shrine Boss", "region": "Submarine Shrine"},
   #10315 Submarine Shrine Boss attack id
    10316: {"name": "White Roundhead Mushroom", "region": "Mist Grove 1"},
    10317: {"name": "White Roundhead Tree", "region": "Mist Grove 1"},
    10318: {"name": "Green Gel Bat", "region": "Mist Grove 1"},
    10319: {"name": "White Boss Roundhead Mushroom", "region": "Mist Grove 1"},
    10320: {"name": "Yellow Roundhead Bat", "region": "Mist Grove 2"},
    10321: {"name": "Yellow Roundhead Dragon", "region": "Mist Grove 2"},
    10322: {"name": "Orange Roundhead Tree (Mist Grove 2)", "region": "Mist Grove 2"},
    10323: {"name": "Orange Boss Roundhead Tree", "region": "Mist Grove 2"},
    10324: {"name": "Green Gel Wheel", "region": "Mist Grove 3"},
    10325: {"name": "Olive Roundhead Stickman", "region": "Mist Grove 3"},
    10326: {"name": "Olive Star Mushroom", "region": "Mist Grove 3"},
    10327: {"name": "Olive Boss Star Tree", "region": "Mist Grove 3"},
    10328: {"name": "Pink Gel Spider", "region": "???"},
    10329: {"name": "Pink Boss Gel Spider", "region": "???"},
    10330: {"name": "Tan Box Spider", "region": "Desert 1"},
    10331: {"name": "Tan Box Snake", "region": "Desert 1"},
    10332: {"name": "Grey Box Walker", "region": "Desert 1"},
    10333: {"name": "Grey Boss Box Walker", "region": "Desert 1"},
    10334: {"name": "Tan Box Bat (Desert 2)", "region": "Desert 2"},
    10335: {"name": "Red Box Dragon", "region": "Desert 2"},
    10336: {"name": "Grey Box Wheel", "region": "Desert 2"},
    10337: {"name": "Grey Boss Box Walker", "region": "Desert 2"},
    10338: {"name": "Green Diamond Cactus", "region": "Desert 3"},
    10339: {"name": "Pink Diamond Cactus", "region": "Desert 3"},
    10340: {"name": "Orange Box Cactus", "region": "Desert 3"},
    10341: {"name": "Yellow Boss Diamond Cactus", "region": "Desert 3"},
    10342: {"name": "Orange Box Bat", "region": "Desert 4"},
    10343: {"name": "White Diamond Cactus", "region": "Desert 4"},
    10344: {"name": "Orange Diamond Spider", "region": "Desert 4"},
    10345: {"name": "Orange Boss Diamond Spider", "region": "Desert 4"},
    10346: {"name": "Red Big Diamond Spider", "region": "Desert 5"},
    10347: {"name": "Yellow Big Diamond Cactus", "region": "Desert 5"},
    10348: {"name": "Cyan Box Eel", "region": "Desert 5"},
    10349: {"name": "White Boss Box Stickman", "region": "Desert 5"},
    10350: {"name": "White Box Eel", "region": "Oasis"},
    10351: {"name": "Green Diamond Eel", "region": "Oasis"},
    10352: {"name": "Red Box Eel", "region": "Oasis"},
    10353: {"name": "Yellow Boss Box Eel (Oasis)", "region": "Oasis"},
    10354: {"name": "White Roundhead Zombie", "region": "Desert 6"},
    10355: {"name": "White Skull Bat (Desert 6)", "region": "Desert 6"},
    10356: {"name": "Red Gel Zombie", "region": "Desert 6"},
    10357: {"name": "White Boss Skull Zombie", "region": "Desert 6"},
    10358: {"name": "White Box Zombie", "region": "Desert 7"},
    10359: {"name": "Blue Diamond Bat", "region": "Desert 7"},
    10360: {"name": "Orange Diamond Snake", "region": "Desert 7"},
    10361: {"name": "Orange Boss Diamond Snake", "region": "Desert 7"},
    10362: {"name": "Pyramid Boss", "region": "Pyramid"},
   #10363 Pyramid Boss attack id
    10364: {"name": "Yellow Roundhead Spider", "region": "Desert 8"},
    10365: {"name": "Orange Big Roundhead Spider", "region": "Desert 8"},
    10366: {"name": "Grey Box Tree", "region": "Desert 8"},
    10367: {"name": "Red Boss Box Tree", "region": "Desert 8"},
    10368: {"name": "Orange Skull Spider", "region": "Beach 1"},
    10369: {"name": "Olive Gel Dragon", "region": "Beach 1"},
    10370: {"name": "White Big Vampire Fish", "region": "Beach 1"},
    10371: {"name": "White Boss Vampire Fish", "region": "Beach 1"},
    10372: {"name": "Cyan Fairy Bat", "region": "Beach 2"},
    10373: {"name": "Blue Fairy Dragon", "region": "Beach 2"},
    10374: {"name": "White Vampire Eel", "region": "Beach 2"},
    10375: {"name": "Orange Boss Vampire Eel", "region": "Beach 2"},
    10376: {"name": "Tan Big Box Snake", "region": "Beach 3"},
    10377: {"name": "Cyan Box Fish", "region": "Beach 3"},
    10378: {"name": "Green Vampire Tree", "region": "Beach 3"},
    10379: {"name": "Yellow Boss Vampire Eel", "region": "Beach 3"},
    10380: {"name": "Grey Shield Bat", "region": "Cavern 4"},
    10381: {"name": "Red Shield Bat", "region": "Cavern 4"},
    10382: {"name": "Green Shield Dragon", "region": "Cavern 4"},
    10383: {"name": "Red Boss Shield Bat", "region": "Cavern 4"},
    10384: {"name": "Blue Shield Eel", "region": "Cavern 4"},
    10385: {"name": "White Shield Bat", "region": "Cavern 5"},
    10386: {"name": "Pink Shield Zombie", "region": "Cavern 5"},
    10387: {"name": "Green Shield Zombie", "region": "Cavern 5"},
    10388: {"name": "Red Boss Shield Zombie", "region": "Cavern 5"},
    10389: {"name": "Blue Big Shield Eel", "region": "Cavern 5"},
    10390: {"name": "Green Shield Bat", "region": "Cavern 6"},
    10391: {"name": "Orange Shield Bat", "region": "Cavern 6"},
    10392: {"name": "Yellow Shield Bat", "region": "Cavern 6"},
    10393: {"name": "Red Boss Shield Tree", "region": "Cavern 6"},
    10394: {"name": "Yellow Shield Eel", "region": "Cavern 6"},
    10395: {"name": "White Roundhead Snake (Snowfield 1)", "region": "Snowfield 1"},
    10396: {"name": "Grey X Walker (Snowfield 1)", "region": "Snowfield 1"},
    10397: {"name": "Cyan X Walker", "region": "Snowfield 1"},
    10398: {"name": "White Boss X Walker (Snowfield 1)", "region": "Snowfield 1"},
    10399: {"name": "White Castle Stickman", "region": "Snowfield 2"},
    10400: {"name": "Grey Big Castle Stickman", "region": "Snowfield 2"},
    10401: {"name": "Pink Big Castle Stickman", "region": "Snowfield 2"},
    10402: {"name": "White Boss Castle Stickman (Snowfield 2)", "region": "Snowfield 2"},
    10403: {"name": "Red Diamond Tree", "region": "Mountain 1"},
    10404: {"name": "Olive Diamond Tree", "region": "Mountain 1"},
    10405: {"name": "Blue Diamond Wheel", "region": "Mountain 1"},
    10406: {"name": "Grey Boss Castle Wheel", "region": "Mountain 1"},
    10407: {"name": "Red Roundhead Copter", "region": "Mountain 2"},
    10408: {"name": "Grey Castle Stickman", "region": "Mountain 2"},
    10409: {"name": "Grey Big X Walker", "region": "Mountain 2"},
    10410: {"name": "Red Boss Roundhead Copter", "region": "Mountain 2"},
    10411: {"name": "Red Boss Smiley Eel", "region": "Mountaintop"},
    10412: {"name": "Blue Boss Fairy Eel", "region": "Mountaintop"},
    10413: {"name": "Olive Boss Star Eel", "region": "Mountaintop"},
    10414: {"name": "Green Boss Cap Eel", "region": "Mountaintop"},
    10415: {"name": "Brown Shield Bat", "region": "Snowfield 3"},
    10416: {"name": "Cyan Shield Spider", "region": "Snowfield 3"},
    10417: {"name": "Purple Gel Tree", "region": "Snowfield 3"},
    10418: {"name": "White Boss Castle Dragon", "region": "Snowfield 3"},
    10419: {"name": "Yellow Big Diamond Tree", "region": "Snowfield 4"},
    10420: {"name": "Green Big Vampire Mushroom", "region": "Snowfield 4"},
    10421: {"name": "Grey Big Box Spider", "region": "Snowfield 4"},
    10422: {"name": "White Boss Castle Stickman (Snowfield 4)", "region": "Snowfield 4"},
    10423: {"name": "Pink Roundhead Dragon", "region": "Snowfield 5"},
    10424: {"name": "Pink Diamond Dragon", "region": "Snowfield 5"},
    10425: {"name": "White Big X Walker", "region": "Snowfield 5"},
    10426: {"name": "White Boss Vampire Tree", "region": "Snowfield 5"},
    10427: {"name": "Pink X Walker", "region": "Snowfield 6"},
    10428: {"name": "Orange X Walker", "region": "Snowfield 6"},
    10429: {"name": "Yellow Mask Tree", "region": "Snowfield 6"},
    10430: {"name": "Orange Boss Castle Stickman", "region": "Snowfield 6"},
    10431: {"name": "Blue Diamond Mushroom", "region": "Snowfield 7"},
    10432: {"name": "White Big Vampire Snake", "region": "Snowfield 7"},
    10433: {"name": "Orange Castle Snake", "region": "Snowfield 7"},
    10434: {"name": "White Boss Castle Snake", "region": "Snowfield 7"},
    10435: {"name": "White Shield Snake", "region": "Snowfield 8"},
    10436: {"name": "Yellow Shield Snake", "region": "Snowfield 8"},
    10437: {"name": "Orange Big Gel Tree", "region": "Snowfield 8"},
    10438: {"name": "Yellow Boss Gel Tree", "region": "Snowfield 8"},
    10439: {"name": "Blue Shield Copter", "region": "Frozen Lake"},
    10440: {"name": "White Big Fairy Snake", "region": "Frozen Lake"},
    10441: {"name": "Yellow Big Gel Tree", "region": "Frozen Lake"},
    10442: {"name": "White Boss Vampire Mushroom", "region": "Frozen Lake"},
    10443: {"name": "Ice Castle Boss", "region": "Ice Castle"},
   #10444 Ice Castle Boss attack id
    10445: {"name": "Grey Roundhead Tree", "region": "Snowfield 9"},
    10446: {"name": "White Roundhead Copter", "region": "Snowfield 9"},
    10447: {"name": "White Roundhead Walker", "region": "Snowfield 9"},
    10448: {"name": "Pink Boss Roundhead Tree", "region": "Snowfield 9"},
    10449: {"name": "Pink Demon Fish", "region": "Beach 4"},
    10450: {"name": "Red Coconut Spider", "region": "Beach 4"},
    10451: {"name": "Yellow Demon Eel", "region": "Beach 4"},
    10452: {"name": "White Boss Demon Eel", "region": "Beach 4"},
    10453: {"name": "Orange Roundhead Tree (Forest 3)", "region": "Forest 3"},
    10454: {"name": "Pink Roundhead Mushroom", "region": "Forest 3"},
    10455: {"name": "Pink Coconut Copter", "region": "Forest 3"},
    10456: {"name": "Yellow Boss Coconut Wheel", "region": "Forest 3"},
    10457: {"name": "Green Gel Bouncer", "region": "Forest 4"},
    10458: {"name": "Green Big Gel Bouncer", "region": "Forest 4"},
    10459: {"name": "Green Boss Gel Bouncer", "region": "Forest 4"},
    10460: {"name": "Orange Roundhead Stickman", "region": "Forest 5"},
    10461: {"name": "Yellow Roundhead Stickman", "region": "Forest 5"},
    10462: {"name": "Blue Roundhead Stickman", "region": "Forest 5"},
    10463: {"name": "Grey Boss Demon Stickman", "region": "Forest 5"},
    10464: {"name": "Grey Big Box Snake", "region": "Forest 6"},
    10465: {"name": "Tan Box Bat (Forest 6)", "region": "Forest 6"},
    10466: {"name": "Green Box Bouncer", "region": "Forest 6"},
    10467: {"name": "Grey Boss Box Snake", "region": "Forest 6"},
    10468: {"name": "Purple Coconut Germ", "region": "!!!"},
    10469: {"name": "Pink Boss Coconut Germ", "region": "!!!"},
    10470: {"name": "White Triangle Stickman", "region": "Hell 1"},
    10471: {"name": "Orange Triangle Stickman", "region": "Hell 1"},
    10472: {"name": "Grey Triangle Walker", "region": "Hell 1"},
    10473: {"name": "Grey Boss Triangle Walker", "region": "Hell 1"},
    10474: {"name": "White Triangle Germ", "region": "Hell 2"},
    10475: {"name": "Yellow Big Coconut Snake", "region": "Hell 2"},
    10476: {"name": "Green Big Diamond Tree", "region": "Hell 2"},
    10477: {"name": "Grey Boss Triangle Tree", "region": "Hell 2"},
    10478: {"name": "White Triangle Cactus", "region": "Hell 3"},
    10479: {"name": "Cyan Big Triangle Cactus", "region": "Hell 3"},
    10480: {"name": "Orange Roundhead Snake", "region": "Hell 3"},
    10481: {"name": "Orange Boss Roundhead Walker", "region": "Hell 3"},
    10482: {"name": "Green Roundhead Digger", "region": "Hell 4"},
    10483: {"name": "Cyan Triangle Digger", "region": "Hell 4"},
    10484: {"name": "Orange Box Digger", "region": "Hell 4"},
    10485: {"name": "Tan Boss Diamond Tree", "region": "Hell 4"},
    10486: {"name": "Grey Big Box Stickman (Bullet)", "region": "Hell 5"},
    10487: {"name": "Grey Big Box Stickman (Spear)", "region": "Hell 5"},
    10488: {"name": "Grey Big Box Stickman (Two Arrow)", "region": "Hell 5"},
    10489: {"name": "Grey Boss Box Stickman", "region": "Hell 5"},
    10490: {"name": "Yellow Triangle Bat", "region": "Hell 6"},
    10491: {"name": "Green Coconut Germ", "region": "Hell 6"},
    10492: {"name": "Orange Demon Dragon", "region": "Hell 6"},
    10493: {"name": "Blue Boss Gel Mushroom", "region": "Hell 6"},
    10494: {"name": "Pink Demon Stickman", "region": "Inferno 1"},
    10495: {"name": "White Demon Stickman", "region": "Inferno 1"},
    10496: {"name": "Pink Big Triangle Walker", "region": "Inferno 1"},
    10497: {"name": "White Boss Triangle Walker", "region": "Inferno 1"},
    10498: {"name": "Tan Triangle Tree", "region": "Inferno 2"},
    10499: {"name": "Cyan Triangle Tree", "region": "Inferno 2"},
    10500: {"name": "Purple Triangle Cactus", "region": "Inferno 2"},
    10501: {"name": "Yellow Boss Coconut Walker", "region": "Inferno 2"},
    10502: {"name": "Orange Coconut Spider", "region": "Inferno 3"},
    10503: {"name": "Yellow Coconut Spider", "region": "Inferno 3"},
    10504: {"name": "Blue Coconut Spider", "region": "Inferno 3"},
    10505: {"name": "Green Boss Coconut Spider", "region": "Inferno 3"},
    10506: {"name": "Orange Box Fish", "region": "Blood Lake"},
    10507: {"name": "Green Box Tree", "region": "Blood Lake"},
    10508: {"name": "Blue Box Copter", "region": "Blood Lake"},
    10509: {"name": "Brown Boss Box Germ", "region": "Blood Lake"},
    10510: {"name": "Cyan Gel Tree", "region": "Cavern 7"},
    10511: {"name": "Pink Gel Tree (Cavern 7)", "region": "Cavern 7"},
    10512: {"name": "Orange Diamond Bat", "region": "Cavern 7"},
    10513: {"name": "Green Boss Cap Tree", "region": "Cavern 7"},
    10514: {"name": "Yellow Box Germ (Cavern 7)", "region": "Cavern 7"},
    10515: {"name": "Yellow Cap Tree", "region": "Cavern 8"},
    10516: {"name": "Blue Cap Tree", "region": "Cavern 8"},
    10517: {"name": "Red Diamond Snake", "region": "Cavern 8"},
    10518: {"name": "Red Boss Gel Tree (Cavern 8)", "region": "Cavern 8"},
    10519: {"name": "Yellow Box Germ (Cavern 8)", "region": "Cavern 8"},
    10520: {"name": "Green Box Wheel", "region": "Hell 7"},
    10521: {"name": "Brown Big Box Wheel", "region": "Hell 7"},
    10522: {"name": "Yellow Big Box Wheel", "region": "Hell 7"},
    10523: {"name": "Red Boss Box Wheel", "region": "Hell 7"},
    10524: {"name": "Cyan Triangle Snake", "region": "Hell 8"},
    10525: {"name": "Grey Big Diamond Germ", "region": "Hell 8"},
    10526: {"name": "Grey Big Mask Eel", "region": "Hell 8"},
    10527: {"name": "Pink Boss Triangle Snake", "region": "Hell 8"},
    10528: {"name": "White Skull Stickman (Hell Gate)", "region": "Hell Gate"},
    10529: {"name": "Red Skull Stickman (Hell Gate)", "region": "Hell Gate"},
    10530: {"name": "Red X Walker", "region": "Hell Gate"},
    10531: {"name": "White Boss Skull Stickman (Hell Gate)", "region": "Hell Gate"},
    10532: {"name": "Hell Castle Boss", "region": "Hell Castle"},
   #10533 Hell Castle Boss attack id
   #10534 Hell Castle Boss attack id
   #10535 Hell Castle Boss attack id
   #10536 Hell Castle Boss attack id
   #10537 Hell Castle Boss attack id
    10538: {"name": "Yellow Boss Box Eel (Volcano)", "region": "Volcano"},
   #10539 Map sign spawning
}

location_table: Dict[int, LocationDict] = {}
location_table.update(stages_table)
location_table.update(books_table)
location_table.update(enemies_table)

location_name_to_id = {
    value['name']: id
    for id, value in location_table.items()
}

lookup_id_to_name: Dict[int, str] = {
    data: item_name for item_name, data in location_name_to_id.items() if data
}
