region_info = {
    "regions": [
        ["Menu", ["New Game"]],
        ["Grassland", ["Castle"]],
        ["Sea", ["Submarine Shrine"]],
        ["Desert", ["Pyramid"]],
        ["Snow", ["Ice Castle"]],
        ["Hell", []]
    ],
    "mandatory_connections": [
        ["New Game", "Grassland"],
        ["Castle", "Sea"],
        ["Submarine Shrine", "Desert"],
        ["Pyramid", "Snow"],
        ["Ice Castle", "Hell"]
    ]
}

locations_by_region = {
    "Grassland": [
        "Opening Street",
        "Opening Street Book",
        "Grassland 1",
        "Grassland 1 Book",
        "Grassland 2",
        "Grassland 2 Book",
        "Grassland 3",
        "Grassland 3 Book",
        "Grassland 4",
        "Grassland 4 Book",
        "Grassland 5",
        "Grassland 5 Book",
        "Grassland 6",
        "Grassland 6 Book",
        "Grassland 7",
        "Grassland 7 Book",
        "Lake",
        "Lake Book",
        "Hill Country 1",
        "Hill Country 1 Book",
        "Hill Country 2",
        "Hill Country 2 Book",
        "Hill Country 3",
        "Hill Country 3 Book",
        "Forest 1",
        "Forest 1 Book",
        "Forest 2",
        "Forest 2 Book",
        "Cavern 1",
        "Cavern 1 Book",
        "Cavern 2",
        "Cavern 2 Book",
        "Cavern 3",
        "Cavern 3 Book",
        "Castle Gate",
        "Castle Gate Book",
        "Castle",
        "Castle Book",
        "Village"
    ],
    "Sea": [
        "Seaside 1",
        "Seaside 1 Book",
        "Seaside 2",
        "Seaside 2 Book",
        "Seaside 3",
        "Seaside 3 Book",
        "Seaside 4",
        "Seaside 4 Book",
        "Mist Grove 1",
        "Mist Grove 1 Book",
        "Mist Grove 2",
        "Mist Grove 2 Book",
        "Mist Grove 3",
        "Mist Grove 3 Book",
        "???",
        "??? Book",
        "Submarine 1",
        "Submarine 1 Book",
        "Submarine 2",
        "Submarine 2 Book",
        "Submarine 3",
        "Submarine 3 Book",
        "Submarine 4",
        "Submarine 4 Book",
        "Submarine Shrine",
        "Submarine Shrine Book"
    ],
    "Desert": [
        "Desert 1",
        "Desert 1 Book",
        "Desert 2",
        "Desert 2 Book",
        "Desert 3",
        "Desert 3 Book",
        "Desert 4",
        "Desert 4 Book",
        "Desert 5",
        "Desert 5 Book",
        "Oasis",
        "Oasis Book",
        "Desert 6",
        "Desert 6 Book",
        "Desert 7",
        "Desert 7 Book",
        "Desert 8",
        "Desert 8 Book",
        "Beach 1",
        "Beach 1 Book",
        "Beach 2",
        "Beach 2 Book",
        "Beach 3",
        "Beach 3 Book",
        "Pyramid",
        "Pyramid Book",
        "Resort"
    ],
    "Snow": [
        "Cavern 4",
        "Cavern 4 Book",
        "Cavern 5",
        "Cavern 5 Book",
        "Cavern 6",
        "Cavern 6 Book",
        "Snowfield 1",
        "Snowfield 1 Book",
        "Snowfield 2",
        "Snowfield 2 Book",
        "Snowfield 3",
        "Snowfield 3 Book",
        "Snowfield 4",
        "Snowfield 4 Book",
        "Snowfield 5",
        "Snowfield 5 Book",
        "Snowfield 6",
        "Snowfield 6 Book",
        "Snowfield 7",
        "Snowfield 7 Book",
        "Snowfield 8",
        "Snowfield 8 Book",
        "Mountain 1",
        "Mountain 1 Book",
        "Mountain 2",
        "Mountain 2 Book",
        "Mountaintop",
        "Mountaintop Book",
        "Frozen Lake",
        "Frozen Lake Book",
        "Ice Castle",
        "Ice Castle Book"
    ],
    "Hell": [
        "Snowfield 9",
        "Snowfield 9 Book",
        "!!!",
        "!!! Book",
        "Beach 4",
        "Beach 4 Book",
        "Forest 3",
        "Forest 3 Book",
        "Forest 4",
        "Forest 4 Book",
        "Forest 5",
        "Forest 5 Book",
        "Forest 6",
        "Forest 6 Book",
        "Hell 1",
        "Hell 1 Book",
        "Hell 2",
        "Hell 2 Book",
        "Hell 3",
        "Hell 3 Book",
        "Hell 4",
        "Hell 4 Book",
        "Hell 5",
        "Hell 5 Book",
        "Hell 6",
        "Hell 6 Book",
        "Cavern 7",
        "Cavern 7 Book",
        "Cavern 8",
        "Cavern 8 Book",
        "Hell 7",
        "Hell 7 Book",
        "Hell 8",
        "Hell 8 Book",
        "Hell Gate",
        "Hell Gate Book",
        "Hell Castle",
        "Hell Castle Book",
        "Inferno 1",
        "Inferno 1 Book",
        "Inferno 2",
        "Inferno 2 Book",
        "Inferno 3",
        "Inferno 3 Book",
        "Blood Lake",
        "Blood Lake Book",
        "Volcano",
        "Volcano Book",
        "Forget Tree",
        "Island"
    ]
}